<?php
//philum_microsql_admin_params
$r["_menus_"]=array('category','name');
$r[1]=array('config','modules_table');
$r[2]=array('access','automember');
$r[3]=array('articles','kmax');
$r[4]=array('access','viewport');
$r[5]=array('access','auto_design');
$r[6]=array('articles','nb_arts_by_page');
$r[9]=array('articles','art_order');
$r[11]=array('access','new_users');
$r[16]=array('config','nb_days');
$r[17]=array('config','date_format');
$r[18]=array('meta','usertags');
$r[19]=array('meta','usertags:pictos');
$r[21]=array('articles','forbidden_images');
$r[23]=array('config','upload_extensions');
$r[24]=array('access','maj_server');
$r[25]=array('access','lang');
$r[26]=array('meta','articles_lang');
$r[27]=array('config','thumbnails');

?>