<?php //msql/admin_apps
$r=["_menus_"=>['button','type','process','param','option','condition','root','icon','hide'],
"1"=>['Desktop','ajax','page','deskload','','tools','','admin',''],
"2"=>['site','ajax','popup','site___desktop_ok__autosize','','menu tools','','global',''],
"3"=>['new art','ajax','popup','addArt____1','','tools','','editor',''],
"4"=>['finder','finder','','','shared/global//flap///mini_1','menu tools','','network','1'],
"5"=>['editor','admin','editor','','','menu tools','edit/art','editor',''],
"6"=>['sText','plug','stext','','','menu tools','edit/art','editor',''],
"7"=>['sticky','plug','sticky','','self','menu tools','edit','editor',''],
"8"=>['notepad','plug','notepad','','','menu tools','edit','editor',''],
"9"=>['mail','plug','mail','','','menu tools','com','mail',''],
"10"=>['chat','plug','chat','','','menu tools','com','chat',''],
"11"=>['twitter','plug','twit','','','menu tools','com','chat',''],
"12"=>['update-notes','msql','system','program','updates_1212','menu tools','user','server',''],
"13"=>['updates-table','ajax','popup','msql___system_program_updates_1301','','menu tools','user','msql',''],
"14"=>['recents','mod','recents','public','/scroll/10','tools','user','get',''],
"15"=>['system','admin','console','system','','menu tools','user','builders',''],
"16"=>['article','art','auto','418','','tools','','',''],
"17"=>['ixquick','link','','https://www.ixquick.com/fra/','','tools','','search',''],
"18"=>['web','plug','ixquick','','','tools','','search','1'],
"19"=>['iframe','plug','ifram','','','menu tools','','','']];