<?php
//philum_microsql_connectors_basic
$r["_menus_"]=array('type','param');
$r["[ ]"]=array('embed','[\',\']');
$r["url"]=array('SaveJ','popup_url');
$r["img"]=array('embed','');
$r["video"]=array('embed','');
$r["h"]=array('embed','');
$r["b"]=array('embed','');
$r["i"]=array('embed','');
$r["u"]=array('embed','');
$r["s"]=array('embed','');
$r["r"]=array('embed','');
$r["k"]=array('embed','');
$r["l"]=array('embed','');
$r["center"]=array('embed','');
$r["right"]=array('embed','');
$r["table"]=array('embed','');
$r["list"]=array('embed','');
$r["q"]=array('embed','');
$r["notes"]=array('embed','');
$r["--"]=array('insert','[--]');
$r["nbsp"]=array('insert','&nbsp;');
$r["select"]=array('document.getElementById(\'txtarea\').select()','');
$r["copy"]=array('mem_storage','_m0');
$r["paste"]=array('mem_storage','_m0_1');
$r["deline"]=array('embed_slct','\',\'\',\'\',\'clean_n');
$r["delconn"]=array('conn','_delconn');
$r["findconn"]=array('autoslct','txtarea');
$r["del"]=array('conn','_del');
$r["nl"]=array('insert','n');
$r["mktable"]=array('embed_slct','\',\'\',\'\',\'mktable');

?>