<?php
//philum_microsql_connectors_old
$r["_menus_"]=array('new');
$r["{{"]=array('[');
$r["}}"]=array(':q]');
$r[".tit"]=array(':h');
$r[":tit"]=array(':h');
$r[".tib"]=array(':h4');
$r[":tib"]=array(':h4');
$r[":pub1"]=array('§1:pub');
$r[":pub2"]=array('§2:pub');
$r[":pub3"]=array('§3:pub');
$r[":livestream"]=array(':video');
$r[":dailymotion"]=array(':video');
$r[":youtube"]=array(':video');
$r[":google"]=array(':video');
$r[":vimeo"]=array(':video');
$r[":ted"]=array(':video');
$r[":jukebox2"]=array('§2:jukebox');
$r[":msq_template"]=array(':msq_read');
$r[":msq_ads"]=array(':msq_conn');
$r[":microform"]=array(':msq_form');
$r[":microsql"]=array(':msql');
$r[":polaroid"]=array(':figure');
$r[":popvideo"]=array(':video');
$r[":2cols"]=array(':cols');
$r[":3cols"]=array(':cols');
$r[":/2"]=array(':block');
$r[":/3"]=array(':block');
$r[":twit_cache"]=array(':twitter');
$r[":poptwit"]=array(':twitter');

?>