<?php
//philum_microsql_connectors_tools
$r["_menus_"]=array('type','param','category');
$r[":(x)"]=array('conn','_delconn','del');
$r[":b"]=array('conn','_delconn_b','del');
$r[":c"]=array('conn','_delconn_c','del');
$r[":h"]=array('conn','_delconn_h','del');
$r[":h2"]=array('conn','_delconn_h2','del');
$r[":i"]=array('conn','_delconn_i','del');
$r[":list"]=array('conn','_delconn_list','del');
$r[":no"]=array('conn','_delconn_no','del');
$r[":q"]=array('conn','_delconn_q','del');
$r[":s"]=array('conn','_delconn_s','del');
$r[":u"]=array('conn','_delconn_u','del');
$r["?"]=array('SaveJ','txarea_filters_txtarea__delqmark','del');
$r["add_lines"]=array('SaveJ','txarea_filters_txtarea__addlines','filters');
$r["clean_br"]=array('SaveJ','txarea_filters_txtarea__cleanbr','filters');
$r["clean_mail"]=array('SaveJ','txarea_filters_txtarea__cleanmail','filters');
$r["convert_html"]=array('SaveJ','txarea_filters_txtarea__converthtml','filters');
$r["css"]=array('SaveJ','popup_emdpop___css','html');
$r["footnotes"]=array('SaveJ','txarea_filters_txtarea__addanchors','tools');
$r["img_label"]=array('SaveJ','txarea_filters_txtarea__imglabel','filters');
$r["import"]=array('SaveJ','popup_emdpop___call*url','tools');
$r["last_saved"]=array('revert()','','tools');
$r["lines"]=array('embed_slct','\',\'\',\'\',\'clean_n ','del');
$r["lowcase"]=array('embed_slct','\',\'\',\'\',\'lowercase','filters');
$r["old_conn"]=array('SaveJ','txarea_filters_txtarea__oldconn','filters');
$r["paste"]=array('SaveJ','popup_emdpop___paste','tools');
$r["punct"]=array('SaveJ','txarea_filters_txtarea__cleanpunct','filters');
$r["rename_img"]=array('SaveJ','txarea_filters_txtarea__randim','filters');
$r["replace"]=array('captslct','replace','filters');
$r["revert"]=array('SaveJ','txarea_filters_txtarea__revert','tools');
$r["tables"]=array('SaveJ','txarea_filters_txtarea__deltables','del');
$r["mktable"]=array('embed_slct','\',\'\',\'\',\'mktable','filters');

?>