<?php
//philum_microsql_connectors_codeline
$r['_menus_']=array('value');
$r['balise']=array('value§balise|id|class');
$r['html']=array('value§balise');
$r['div']=array('value§attributs');
$r['span']=array('value§attributs');
$r['css']=array('value§class');
$r['br']=array('');
$r['id']=array('attribut');
$r['class']=array('attribut');
$r['style']=array('attribut');
$r['name']=array('attribut');
$r['text']=array('value');
$r['url']=array('value§param');
$r['link']=array('value§param');
$r['anchor']=array('value');
$r['date']=array('value§param');
$r['title']=array('param');
$r['read']=array('ID§preview');
$r['image']=array('value');
$r['thumb']=array('value§width/height');
$r['split']=array('string§cutter');
$r['cut']=array('text§start/end');
$r['conn']=array('connparams§conn');
$r['plug']=array('plug§param');
$r['core']=array('p1/p2/p3§function');

?>