<?php
//philum_microsql_default_apps_menu_sav
$r["_menus_"]=array('button','type','process','param','option','condition','root','icon','hide','private');
$r[1]=array('home','link','','/home','','menu','','home','','');
$r[2]=array('home','url','','/home','','menu','','home','','');
$r[3]=array('all','url','','all','','menu','','globe','','');
$r[4]=array('admin','url','','/?admin==&log=open','','menu','','admin','','');
$r[5]=array('codev','plug','plug','codev_plug_lib','','menu','dev','edit','','7');
$r[16]=array('exec','plug','plug','exec_plug_lib','','menu','dev','edit','','7');
$r[6]=array('root','ajax','popup','desktop___desk','','menu','','folder2','','');
$r[7]=array('philumsize','link','','/plugin/philumsize','','menu','dev','phi','','6');
$r[8]=array('desk','ajax','desktop','desk','','menu','','folder','','');
$r[9]=array('folder','ajax','popup','modpop__3_local|real//////folder2///1:desktop*files_480','','menu','','folder','','');
$r[10]=array('article','ajax','popup','popart__3_ID_3','','menu','','articles','','');
$r[11]=array('search','ajax','popup','search','','menu','','search','','');
$r[12]=array('taxonav','ajax','popup','plup___taxonav','','menu','','topo','','');
$r[13]=array('taxonav','plug','taxonav','','','menu','','topo','','');

?>