<?php
//philum_microsql_default_apps
$r["_menus_"]=array('button','type','process','param','option','condition','root','icon','hide','private');
$r[1]=array('Desktop','ajax','page','deskload__18_boot','','menu','os','desktop','','');
$r[2]=array('Root','ajax','desktop','desk___desk','','boot','os','desktop','','');
$r[3]=array('Root Folder','ajax','popup','desktop___desk','','menu','os','folder2','','');
$r[4]=array('Background','ajax','page','deskbkg','','boot','os','desktop','','');
$r[5]=array('Site','ajax','popup','site___desktop_ok__autosize','','root','','window','','');
$r[6]=array('Close Desktop','ajax','page','deskoff___module_Home','','menu','os','home','','');
$r[7]=array('Articles virtuels','mod','desktop_varts','cache','','desk','Articles','virtual','1','');
$r[8]=array('Articles','mod','desktop_arts','cat=public|pub~nbdays=30','','desk','Articles','virtual','1','');
$r[9]=array('recents','mod','recents','public','/icons/','desk','Articles','virtual','1','');
$r[10]=array('article','art','auto','418','','desk','','articles','1','');
$r[11]=array('Fichiers','mod','desktop_files','local|virtual','//dev|img','desk','','folder2','','');
$r[12]=array('New art','ajax','popup','addArt____1','','desk','','add','1','1');
$r[13]=array('Finder','finder','','','shared/global//flap///mini_1 ','menu','','finder','','');
$r[14]=array('recherche','ajax','popup','search__3','','menu','','search','','');
$r[15]=array('transductor','plug','iframe','/plug/editor','720/440','menu desk','edit','editxt','','1');
$r[16]=array('pad','plug','pad','','','menu desk','edit','editor','','');
$r[17]=array('txt','plug','txt','','','menu desk','edit','editor','','');
$r[18]=array('sticky','plug','sticky','','','menu desk','edit','sticky','','');
$r[19]=array('mail','plug','mail','','','menu desk','com','mail','','');
$r[20]=array('chat','plug','chatxml','public','','menu desk','com','chat','','');
$r[21]=array('plugin','plug','plug','','','desk menu','com','peak','','');
$r[22]=array('Favs','plug','favs','','','desk','','like','1','');
$r[23]=array('notepad','plug','notepad','','','menu desk','edit','editor','1','');
$r[24]=array('console','admin','console','','','desk menu','sys','admin','1','6');
$r[25]=array('system','admin','console','system','','menu desk','sys','builders','1','6');
$r[26]=array('rstr','admin','restrictions','','','desk menu','sys','true','1','6');
$r[27]=array('apps','ajax','popup','call___adminx_submod*pop','','desk menu','sys','apps','1','6');
$r[28]=array('nouveau','ajax','popup','addArt____1 ','','desk menu','','add','1','2');
$r[29]=array('msql','plug','iframe','/msql/index.php_740','','menu desk','sys','msql','1','4');
$r[30]=array('pictos','admin','pictos','','','menu desk','sys','icons','1','4');
$r[31]=array('updates','ajax','popup','msql___system_program_updates*1511','','menu desk','dev','edit','','7');
$r[32]=array('update-notes','msql','system','program','updates*1511','menu desk','dev','msql','','1');
$r[33]=array('connectors','ajax','popup','msql___system_connectors_all','','menu desk','sys','msql','1','');
$r[34]=array('nominations','ajax','popup','msql___lang_helps_nominations','','menu desk','sys','msql','1','7');
$r[35]=array('helps','ajax','popup','msql___lang_helps_txts','','menu desk','sys','msql','1','4');
$r[36]=array('web','plug','ifram','','740','menu desk','com','shared','1','');
$r[37]=array('links','mod','msql_links','links','','menu','com','url','1','');
$r[38]=array('rss','mod','rss','','','menu','com','rss','','');
$r[39]=array('codeview','plug','codeview','','','desk menu','dev','view','','6');
$r[40]=array('iframe','plug','ifram','','','desk menu','com','view','','');
$r[41]=array('ftext','plug','ftext','','','menu desk','edit','editor','','');
$r[42]=array('twitter','plug','twitter','','','desk menu','com','tw','','');
$r[43]=array('draw','plug','draw','','','menu desk','edit','editor','1','');
$r[44]=array('code','plug','dev','','','menu','dev','phi','','6');
$r[45]=array('imtx','plug','imtx','','','menu desk','edit','edit','','');
$r[46]=array('profil','mod','profil','plug_profil','','user','','user','','1');
$r[47]=array('login','ajax','popup','loged______1','','user','','logout','','0');
$r[48]=array('logout','link','','/logout','','user','','logout','','1');

?>