<?php //philum/microsql/default_mods
$r=["_menus_"=>['block','module','param','title','condition','command','option','cache','hide','template','nobr','div','js','pp'],1=>['system','blocks','banner menu content footer','','','','','','','','','','',''],2=>['system','content','800','','','','','','','','','','',''],5=>['footer','contact','contact','','','','','1','1','','1','','',''],6=>['footer','chrono','','','','','','','0','','1','','',''],7=>['content','prev_next','','','art','','','','','','1','','',''],8=>['content','Page_titles','','','art','','parent','','','','1','','',''],9=>['system','design','2','','','','','','','','','','',''],11=>['newsletter','articles','priority=4&nbdays=1','Articles épiques','','multi','','','','','','','',''],12=>['system','art_mod','//panel/////1:related_arts§lié à,
//panel/////1:related_by§lié par,
tag/Tags//cols///pubart_b/1:see_also-tags§tags,
auteurs/Auteurs//////1:see_also-tags§auteurs,
thèmes/Thèmes//cols////1:see_also-tags§thèmes,
pays/Pays//////1:see_also-tags§pays,
/Sources//////1:see_also-source§source,
/Topologie/icons/////1:taxo_arts§taxo','','','','-','','','','1','','',''],13=>['content','LOAD','','','art','','','','','','1','','',''],16=>['content','connector','[]','','home','','','','1','','','','',''],17=>['newsletter','articles','nbdays:1,nopriority:1|4,preview:auto','Grands titres / 24h','','multi','','','','','','','',''],20=>['newsletter','articles','priority:1,nbdays:1,preview:false','Actu','','multi','','','','','','0','',''],21=>['content','pub_arts','','','home','panel','','','1','','1','','',''],22=>['content','read','','','home','','','','1','','','','',''],23=>['content','articles','','','home','panel','cols','','','','','','',''],31=>['content','related_arts','','Voir aussi','art','','cols','','','pubart_b','','','',''],32=>['content','related_by','','Référencé par','art','','cols','','','pubart_b','','','',''],47=>['content','MenusJ','priority=2|3|4&nbdays=7&preview=auto&nodig=1//-:api_arts§Unes,
priority=1|2&nbdays=2&preview=1&nodig=1:api_arts§Faits,
priority=3&nbdays=7&preview=2&nodig=1:api_arts§Analyses,
priority=4&nbdays=30&preview=2:api_arts§Articulations,
auteurs//-/cols/pubart_b//pubart_b:classtag_arts§Auteurs','','home','onplace','notcloseable','','0','','1','','',''],50=>['menu','link','home','Accueil','','','','','','','','','',''],51=>['menu','MenuBub','','','','','','','','','','','',''],55=>['system','desktop','','','','','','','1','','','','',''],56=>['banner','Banner','','','','','','','1','','','','',''],57=>['content','LOAD','','','cat','','','','','','1','','','']];