<?php //msql/default_params
$r=["_menus_"=>['default','name'],
"1"=>['1','modules_table'],
"2"=>['','auto_member'],
"3"=>['400','kmax'],
"4"=>['','viewport'],
"5"=>['','title_image_font'],
"6"=>['20','nb_arts_by_page'],
"7"=>['1 2 3 4','art_priority'],
"9"=>['id DESC','art_order'],
"11"=>['','new_users'],
"16"=>['','nb_days'],
"17"=>['d/m/Y','date_format'],
"18"=>['auteurs','usertags'],
"19"=>['user','usertags pictos'],
"21"=>['puce.gif puce.png','forbidden_images'],
"23"=>['.7z.psd.rar.pps.webp','upload_extensions'],
"25"=>['LANG','lang'],
"26"=>['fr en es','articles_lang'],
"27"=>['440/320','thumbnails_size']];