<?php
//philum_microsql_default_apps_boot_sav
$r["_menus_"]=array('button','type','process','param','option','condition','root','icon','hide','private');
$r[1]=array('Accueil','link','','/module/Home','','','','home','','');
$r[2]=array('cache','ajax','ajax','rebuild__3xx','','','boot/reset','loading','','4');
$r[3]=array('mini','link','','/?rebuild_img==','','','boot/reset','loading','','4');
$r[4]=array('login','ajax','popup','loged______1','','','boot','logout','','0');
$r[5]=array('reload','link','','/reload','','','boot','reload','','');
$r[6]=array('reboot','link','','/reboot','','','boot','reload','','1');
$r[7]=array('logout','link','','/logout','','','boot','logout','','1');
$r[8]=array('logoff','link','','/logoff','','','boot','logout','','1');
$r[9]=array('shutdown','link','','/shutdown','','','boot','no','','4');
$r[10]=array('tablet','js','android_ui();','','','','utils','gsm','1','');
$r[11]=array('tablet','ajax','socket','plugin__self_tablet','','','utils','gsm','','');
$r[12]=array('favs','plug','favs','','','','','like','1','');
$r[13]=array('dev','link','','/dev','','','','phi','','6');
$r[14]=array('publish','linkt','','/plug/publish_site.php?copy==','','','','txt','1','7');
$r[15]=array('philum','ajax','popup','about','','','','phi2','','');

?>