<?php
//philum_microsql_msql_names
$r["_menus_"]=array('_menus_');
$r[1]=array('edit');
$r[2]=array('backup');
$r[3]=array('restore');
$r[4]=array('get');
$r[5]=array('import');
$r[6]=array('inject');
$r[7]=array('append');
$r[8]=array('combine');
$r[9]=array('new');
$r[10]=array('empty');
$r[11]=array('delete');
$r[12]=array('repair');
$r[13]=array('repair-cols');
$r[14]=array('add_col');
$r[15]=array('del_col');
$r[16]=array('from_conn');
$r[17]=array('to_conn');
$r[18]=array('array');
$r[19]=array('order');
$r[20]=array('reflush');
$r[21]=array('permut');
$r[22]=array('reset_menus');
$r[23]=array('del_menus');
$r[24]=array('add_keys');
$r[25]=array('del_keys');
$r[26]=array('update');
$r[27]=array('backup_msql');

?>