<?php //msql/program_credits
$r=["_menus_"=>['label','url','license','usage'],
"1"=>['philum','http://philum.fr','GPL','CMS'],
"2"=>['jQuery 1.7','http://jquery.com','MIT and GPL','css_builder'],
"3"=>['ColorPicker','http://eyecon.ro','MIT and GPL','css_builder'],
"4"=>['JW Player','http://longtailvideo.com','Creative Commons License (noncommercial)','video player for .flv and .mp4'],
"5"=>['myfonts','http://myfonts.com','(various)','typography'],
"6"=>['fontspring','http://fontspring.com','(various)','typography'],
"7"=>['fontsquirrel','http://fontsquirrel.com','(various)','typography'],
"8"=>['PclTar 1.3.1','http://phpconcept.net','GPL','compression and transport'],
"9"=>['everaldo','http://www.everaldo.com/crystal/','LGPL','iconography'],
"10"=>['ajax_multithread','http://philum.fr','GPL','ajax'],
"11"=>['picol','http://picol.org','Creative Commons','icons'],
"12"=>['thenounproject','http://thenounproject.com','CC BY 3.0','icons'],
"13"=>['FontForge','http://fontforge.org/','revised BSD','Ã©diteur typographique'],
"14"=>['typo Philum','philum.fr','GPL','pictographie']];