<?php
//philum_microsql_program_core
$r["_menus_"]=array('function','variables','usage','return','context');
$r[1]=array('p','r','print_r()','','html');
$r[2]=array('br','','','br balise','html');
$r[3]=array('hr','','','hr balise','html');
$r[4]=array('sep','','separator','','html');
$r[5]=array('atb','d,v','html attribut','d=\"v\"','html');
$r[6]=array('atc','d','class attribut','','html');
$r[7]=array('atd','d','id attribut','','html');
$r[8]=array('ats','d','style attribut','','html');
$r[9]=array('atn','d','name attribut','','html');
$r[10]=array('atv','d','value attribut','','html');
$r[11]=array('atz','d','size attribut','','html');
$r[12]=array('att','d','','','html');
$r[13]=array('atj','d,j','javascript prop and attribut','(\'j\');','html');
$r[14]=array('atjb','r','multiple javascript attributs','','html');
$r[15]=array('sj','d','javascript function SaveJ','SaveJ(\'sj\');','html');
$r[16]=array('atbb','d','multiple attributs: class|id|style','','html');
$r[17]=array('atr','r','multiple props and attributs','','html');
$r[18]=array('ul','v','balise','embed content','html');
$r[19]=array('li','v','balise','embed content','html');
$r[20]=array('bal','b,v','b=balise v=value','balise html','html');
$r[21]=array('balc','b,c,v','balise class value','','html');
$r[22]=array('balb','b,p,v','balise, free manual props, value','','html');
$r[23]=array('balise','b,r,v','b=balise r=attributs t=text :: 
attributs_rule : use key instead of name of property :
array(1=>\"type\",2=>\"name\",3=>\"id\",4=>\"value\",5=>\"class\",6=>\"size\",7=>\"maxlenght\",8=>\"onKeyPress\",9=>\"cols\",10=>\"rows\",11=>\"wrap\",12=>\"action\",13=>\"method\",14=>\"for\",15=>\"onchange\",16=>\"style\")','html balise from an array of attributes','html');
$r[24]=array('balisb','b,r,v','','','html');
$r[25]=array('span','p,v','free props, value','span balise','html');
$r[26]=array('btn','c,v','class text','span balise','html');
$r[27]=array('btd','d,v','id txt','span balise with id value','html');
$r[28]=array('bts','d,v','style value','span balise','html');
$r[29]=array('div','p,v','attributs value','div balise','html');
$r[30]=array('divb','p,v','class|is|style value','div balise','html');
$r[31]=array('divc','c,v','class value','div balise','html');
$r[32]=array('divd','d,v','id value','div balise','html');
$r[33]=array('divs','s,v','style text','div balise','html');
$r[34]=array('button','c,j,v','class javascript text','html button','html');
$r[35]=array('lk','l,p,v','','','html');
$r[36]=array('lka','l,v=\'\'','link value','a balise, display domain only','html');
$r[37]=array('lkc','c,l,v','class link value','a balise','html');
$r[38]=array('lkt','c,l,v','class link value','a balise with target=_blank','html');
$r[39]=array('lkh','oc,ov,v,c=\'\'','onclick js, onhover js, value, class','a balise','html');
$r[40]=array('llk','c,l,v','class link value','a balise inside a li balise','html');
$r[41]=array('submitj','c,id,v','button javascript','button balise','html');
$r[42]=array('lja','j,v,c','','','html');
$r[43]=array('lj','c,j,v,o=\'\'','class js text','a balise with javascript function \'SaveJ\' - shortcut to lc()','html');
$r[44]=array('ljb','c,p,j,v,a=\'\'','class, js function as attribut, js prop, value, 1=onmouseover else onclick','a balise with js and mouseover ability','html');
$r[45]=array('ljc','c,d,j,v,o=\'\',p=\'\'','js button calling a core function :
class, target, js, value, ajaxmode (3=display loading), \'p\' for popup','a balise','html');
$r[46]=array('ljh','c,j,v','on mouseover with timing and autoclose','a balise','html');
$r[47]=array('blj','c,id,j,v','using id as target for answer of ajax','a balise in span balise','html');
$r[48]=array('llj','c,j,v,id=\'\',a=\'\'','class, js, value, id of li, 1=mouseover','a balise in li balise','html');
$r[49]=array('image','d,w=\'\',h=\'\',p=\'\'','image width height props','html embed image','html');
$r[50]=array('img','d','image at 100%','img balise','html');
$r[51]=array('rolloverimg','a,b','switch image on rollover','img button','html');
$r[52]=array('etc','d,n','cut text at n pos and add \"...\"','','html');
$r[53]=array('asciinb','n','','','html');
$r[54]=array('toggle','c,j,v,n=\'\'','class js text','toggle button with ajax call js_function','\'.(9311+n).\';\';}');
$r[55]=array('bubble','c,ja,j,v','class js func, js prop, value','bubble button with ajax call js_function','\'.(9311+n).\';\';}');
$r[56]=array('popbub','d,j,v,c=\'\',o=\'\'','call Apps from bubble','','\'.(9311+n).\';\';}');
$r[57]=array('togbub','ja,j,v,c=\'\',o=\'\'','toggle bubble','','\'.(9311+n).\';\';}');
$r[58]=array('togses','v,t','toggle session','tog button','\'.(9311+n).\';\';}');
$r[59]=array('togses_j','d,t','','','\'.(9311+n).\';\';}');
$r[60]=array('attr','r','','','\'.(9311+n).\';\';}');
$r[61]=array('input','t,d,v,c=\'\',h=\'\',sz=\'\'','type: 1,0 (text,hidden) or any input_type ; id value class','input text for forms','forms');
$r[62]=array('input1','d,v,sz=\'\',c=\'\'','id value size class','input balise','forms');
$r[63]=array('input2','t,n,v,c=\'\'','type name value class','input text for forms','forms');
$r[64]=array('autoclic','n,v,sz,mx,c,h=\'\'','input text auto-hide content','balise input with javascript','forms');
$r[65]=array('jholder','v','old javascript holder','','forms');
$r[66]=array('hidden','n,d,v','name id value','input for forms ','forms');
$r[67]=array('checkbox','n,v,t,chk','chk=0/1 if checked','checkbox for a form','forms');
$r[68]=array('offon','d','','picto true or false','forms');
$r[69]=array('checkbox_j','id,v,t=\'\',b=\'\',c=\'\'','','','forms');
$r[70]=array('checkbob','id,v,a,b','','','forms');
$r[71]=array('checkact','id,v,t','','','forms');
$r[72]=array('label','id,c,s,t','id class style text','label balise connected to id_input (for=\"id\")','forms');
$r[73]=array('radiobtn','r,h,n','','','forms');
$r[74]=array('radiobtj','r,vrf,id,o=\'\'','','','forms');
$r[75]=array('txarea','n,d,cl,rw,c=\'\'','name text cols rows','text area','forms');
$r[76]=array('txareac_btns','','','','forms');
$r[77]=array('txareac','id,c,s,j,d','','','forms');
$r[78]=array('divedit','id,c,s,j,d','','','forms');
$r[79]=array('txarea1','msg,cont','msg, art or track (0/1), continue value (0/1)','textarea used for edit articles, callable from ajax','forms');
$r[80]=array('form','go,d','','','forms');
$r[81]=array('goodarea','v,id,css,j,n','jv=javascripts n=size or cols','balise input text or a textarea','forms');
$r[82]=array('goodarea_b','v,id,c,j,n,h','','','forms');
$r[83]=array('imgform','here,d,t=\'\'','here=url to call cl=class oth=text ttl=title attribut (on rollover)','upload form','forms');
$r[84]=array('upload','d,p','','','forms');
$r[85]=array('upload_btn','id,j,t','','','forms');
$r[86]=array('meta','d,v,c=\'\'','meta d=v and content=c','used by headers','headers');
$r[87]=array('css_link','d,m=\'\'','link to css','used by headers','headers');
$r[88]=array('js_link','d','js link','used by headers','headers');
$r[89]=array('css_code','d','css code','used by headers','headers');
$r[90]=array('js_code','d','js code','used by headers','headers');
$r[91]=array('temporize','name,func,p','name of the function, func=content, p=milliseconds :: temporize() will call a javascript cuntion every p seconds','javascript','headers');
$r[92]=array('relod','v','reload to a page','javascript immediately applied','headers');
$r[93]=array('header_add','d,v','','','headers');
$r[94]=array('headers_balises','r','','used by headers','headers');
$r[95]=array('headers_r','t,r=\'\'','','','headers');
$r[96]=array('connect','','','','mysql');
$r[97]=array('rcptb','db','show tables','mysql_query','mysql');
$r[98]=array('lstrc','rq','make array from range 0 in mysql_fetch_array','array','mysql');
$r[99]=array('msq','ph,bz','build sequence for res() from ph=SELECT attributs and bz=WHERE attributs','formated string','mysql');
$r[100]=array('qr','r','used by rse() and ser()','mysql_fetch_array','mysql');
$r[101]=array('qra','r','','','mysql');
$r[102]=array('qrw','r','','','mysql');
$r[103]=array('res','ph,bz','ph=asked columns bz=where condition','object mysql_fetch_array','mysql');
$r[104]=array('ser','ph,bz','multiple datas of an entry in ph where bz','simple array to use in list($a,$b)=ser($ph,$bz)','mysql');
$r[105]=array('rse','ph,bz','ph=asked column bz=where condition','string result','mysql');
$r[106]=array('msquery','sql','','','mysql');
$r[107]=array('mysql_values','r,d','','','mysql');
$r[108]=array('insert','b,d','','','mysql');
$r[109]=array('update','bs,in,v,col,id','UPDATE bs SET in=v WHERE col=id','nothing (and no error)','mysql');
$r[110]=array('squ','bs,v,w','','','mysql');
$r[111]=array('delete','bs,id','delete in bs where id','nothing','mysql');
$r[112]=array('reflush','bs,o=\'\'','ALTER TABLE bs ORDER BY id :: used by delete()','nothing','mysql');
$r[113]=array('lastid','bs','sql command','id of most recent entry','mysql');
$r[114]=array('sqv','d,n=\'\',b=\'\'','','','mysql');
$r[115]=array('atmres','v','','','mysql');
$r[116]=array('atm','v','','','mysql');
$r[117]=array('atmr','r','','','mysql');
$r[118]=array('atmrup','r','','','mysql');
$r[119]=array('mysqlra','r','','','mysql');
$r[120]=array('mysqlrb','r','','','mysql');
$r[121]=array('sqlformat','rq,p','','','mysql');
$r[122]=array('sql','d,b,p,q,bug=\'\'','','','mysql');
$r[123]=array('sql_b','sql,p,b=\'\'','','','mysql');
$r[124]=array('sql_c','d,b,p,q,bug=\'\'','','','mysql');
$r[125]=array('mkdir_r','u','build directories topology from a string like dir1/dir11/dir111','nothing','dirs');
$r[126]=array('rmdir_r','dr','path dir file topo_number','delete files of a directory, including other dirs ;
option of explode_dir function (used inside a routine)','dirs');
$r[127]=array('explore','dr,p=\'\',o=\'\'','','','dirs');
$r[128]=array('explode_dir','r,d,func','used after explore() in obtain_from_dir()','array of files in $j directory applied to the function $func','dirs');
$r[129]=array('func','d,k,f,n','it\'s an example of func() used  by explode_dir()','string for array built by explode_dir()','dirs');
$r[130]=array('walk_dir','dr,func','','','dirs');
$r[131]=array('read_file','f','open datas from fil f','text','files');
$r[132]=array('write_file','f,t','file_url text to save in f','save file on server','files');
$r[133]=array('get_file','f','','','files');
$r[134]=array('file_get_context','f','','','files');
$r[135]=array('curl_get_contents','f','','','files');
$r[136]=array('joinable','d','','','files');
$r[137]=array('recup_fileinfo','doc','file','formated date and size of a file','files');
$r[138]=array('ftime','f,d=\'\'','file','formated date of a file ','files');
$r[139]=array('fsize','f','file','formated size of a file ','files');
$r[140]=array('fwidth','f','','','files');
$r[141]=array('gz_create','f,fb','file_url bz_name of the compressed archive','store a bz archive','files');
$r[142]=array('gz_write','d,f','bz_url file_name of the decompressed archive','store a file from a bz archive','files');
$r[143]=array('unpack_gz','f,d','','','files');
$r[144]=array('dump','r,p','array of arrays and name of node like \'hub_table\'','prepared values for create_page()','microsql');
$r[145]=array('msq_patch','f,r,nod','','','microsql');
$r[146]=array('msq_menus','r','','','microsql');
$r[147]=array('save_vars','dr,nod,defs','save microtable: directory table defs=array of arrays','nothing','microsql');
$r[148]=array('msql_save','dr,nod,defs,dfb','save array of arrays defs in base/nod adding dfb as _menus_  :: resolve root problems','nothing','microsql');
$r[149]=array('plug_motor','dr,nod,defsb','call a microtable base/nod or create it using _menus_ defsb','array of arrays','microsql');
$r[150]=array('modif_vars','dr,nod,arr,k,dfb=\'\'','  (like hub_table) =array of arrays =\'add\' / \'push\' / \'del\' / value (optionnal)','the modified microtable with $arr','microsql');
$r[151]=array('msql_modif','dr,nod,defs,dfb,act,n','dir node definitions menus action value 
Actions are : 
(defs is a value of a range) :
- one : modif value n
- push : add one value
(defs is the entire table) :
- arr : replace the array 
- mdf : replace value present in defs
- del : deleted values present in defs
- add : add values of defs ; if n=\'mdf\' verif if value already exists before to add it','saved array','microsql');
$r[152]=array('msql_read','dr,nod,in=\'\',u=\'\'','directory nod=table i=range (optionnal) :: resolve root problems','array of a table 
or a part of it 
or only the value there is only one range','microsql');
$r[153]=array('msql_read_b','dr,nod,in=\'\',u=\'\',ra=\'\'','','','microsql');
$r[154]=array('mread','d,l=\'\',c=\'\'','','','microsql');
$r[155]=array('msq_create','d,r,rb,k','','','microsql');
$r[156]=array('msq_where','dr,nod,n,d,o=\'\'','','','microsql');
$r[157]=array('msq_select','dr,pr,nd','select microbases in directory  from user  and table= (in \'bs_\') if theses tables are numeroted','array of needed tables from selection','microsql');
$r[158]=array('msq_find_last','dr,pr,nod','directory hub table','previous empty value to fill (1,2,4 existing return 3)','microsql');
$r[159]=array('msq_find_next','r','array','routine of msq_find_next','microsql');
$r[160]=array('msq_findnext_entry','r,n','','','microsql');
$r[161]=array('msq_goodtable','d','value of a table designed by string command as \'base/node§key\' in a connector ; abble to decide if the key is a number of table or a key of one table','table','microsql');
$r[162]=array('msql_read_prep','b,d','','','microsql');
$r[163]=array('msq_format','r','','','microsql');
$r[164]=array('msq_cat','r,n','array number','make a list form the column of a table (unique key)','microsql');
$r[165]=array('msq_tri','r,n,vrf','array, number, verif','return the values of a column of a table','microsql');
$r[166]=array('msq_sort','r,n,i','','','microsql');
$r[167]=array('msq_reorder','r','reorder the key of a table, beginning from 1','array','microsql');
$r[168]=array('msq_move','r,ka,va','','','microsql');
$r[169]=array('msq_walk','r,n,func,p','array, number, function, param','apply a function with param to each value of a column n','microsql');
$r[170]=array('msq_walk_k','r,func','array, function','apply a function to the keys','microsql');
$r[171]=array('msq_prep','r','affect numeric keys to a table, from 1','table with numerical keys','microsql');
$r[172]=array('msq_prevnext','r,d','','','microsql');
$r[173]=array('msq_copy','da,na,db,nb','','','microsql');
$r[174]=array('msq_n','dr,nod,d','','','microsql');
$r[175]=array('msq_append','defs,d','','','microsql');
$r[176]=array('msq_merge','r,dr,nd','','','microsql');
$r[177]=array('msq_ses','v,dr,nod,u','','','microsql');
$r[178]=array('msq_data','d,o=\'\'','','','microsql');
$r[179]=array('msq_f','dr,nod','','','microsql');
$r[180]=array('make_table','r,csa=\'\',csb=\'\'','datas=array of arrays, csb is only for the first range','balise table','tables');
$r[181]=array('make_divtable','r,h=\'\'','','','tables');
$r[182]=array('make_tables','rt,r,csa,csb','datas=array of arrays, csb is only for the first range, if it is present in titles','balise table','tables');
$r[183]=array('array_conn','r','','','tables');
$r[184]=array('make_tabs','r,ud=\'\',c=\'\'','array with keys used as tabs','html javascript tabs','tables');
$r[185]=array('slct_menus','r,lk,vf,cs1,cs2,kv','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cs1=active cs2=normal css kv=k or v: use key or value','list of links with detection of activated ','menus');
$r[186]=array('slct_menus_tags','r,lk,vf,ct,csa,kv','r=array lk=link (like /?var=) vf=verif (var) ct=if nb is called, render also the number of occurences) cs1=css (use active class if detect var) kv=k/v: use key or value','list of links under li balise with detection of activated ','menus');
$r[187]=array('slctmenusj','r,j,vf,sep,kv=\'\'','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cal=javascript to call','list of links in javascript with detection of selected','menus');
$r[188]=array('slctmenusja','r,j,vf','','','menus');
$r[189]=array('slctmenus_sj','r,go,vf','array, js_command for SaveJ, active value (verif)','list of links calling ajax (SaveJ) with string VAR in js_command replaced by the key of each array','menus');
$r[190]=array('jump_btns','id,v,add,c=\'\'','buttons of values separated by \"|\" in v sent by javascript to id and replacing the input id if add=0 or adding the words in add (like \', \')','buttons who send values in an input','menus');
$r[191]=array('batch_defil','r','array','option balises from keyx of array','menus');
$r[192]=array('menuder_form','r,d','call batch_defil() with r (options) and name the select input d','input select','menus');
$r[193]=array('batch_defil_kv','r,here,kv','array checked_key kk/kv/vv/vk = usage of the values of the array (key-value) :
kk=send and show k;
kv=send k and show v;
vv=send and show v;
vk=send v and show k
-- used by menuder_form_kv','select balise with options and checked_value','menus');
$r[194]=array('menuder_form_kv','r,d,here,kv','build option calling batch_defil_kv() knowing here=selected value and kv=key or value to use for value and title of the options','input select','menus');
$r[195]=array('menuder_h','r,id,d,j','','','menus');
$r[196]=array('menuderj_prep','pr,id,t,opt=\'\'','','','menus');
$r[197]=array('mkbub','d,c=\'\',s=\'\',o=\'\'','','','menus');
$r[198]=array('bubslct','j,t','','','menus');
$r[199]=array('select_jp','id,f,v=\'\',o=\'\',t=\'\'','','','menus');
$r[200]=array('select_jb','id,pr,v=\'\',o=\'\',oj=\'\'','','','menus');
$r[201]=array('select_j','id,f,v=\'\',o=\'\',t=\'\',ty=\'\'','','','select_j //existing_list');
$r[202]=array('msql_slct','id,k,murl','','','select_j //existing_list');
$r[203]=array('read_rss_data','data,t,r','','','rss');
$r[204]=array('read_rss','f,t,r','system/program_functions.php=file_url =master_balise name (like \'item\') =array of sub-balises (like \'title\',\'description\')','array of arrays of an sml or rss source','rss');
$r[205]=array('read_xml','f','','','rss');
$r[206]=array('load_xml','f,o=\'\'','','','rss');
$r[207]=array('mkdts','','','','rss');
$r[208]=array('rss_date','date','find timestamp from rss formated date','timestamp','rss');
$r[209]=array('rss_time','date','','','rss');
$r[210]=array('mkday','d=\'\',p=\'\'','timestamp','datadav using \'ymd\'','dates');
$r[211]=array('calc_date','d','d=timestamp','timestamp of $d days before','dates');
$r[212]=array('calctime','d','','','dates');
$r[213]=array('mtime','','','','dates');
$r[214]=array('timelang','','','','dates');
$r[215]=array('time_prev','d','','','dates');
$r[216]=array('time_ago','dt','php date(dt,df=timestamp) use relative time','formated string like \'2h 10min ago\'','dates');
$r[217]=array('timetravel','','','','dates');
$r[218]=array('on2cols','r,w,p','r is an array with key=label and value=content, w=total width, with of labels=1/p','table in divs','builders');
$r[219]=array('onxcols','re,prm,w,h=\'\'','','','builders');
$r[220]=array('scroll','r,d,n,w=\'\',h=\'\'','obj=array used to build txt, nb is the limit for create a scrool','div with ovrflow if needed','builders');
$r[221]=array('scroll_b','r,d,n,w=\'\',h=\'\',id=\'\'','','','builders');
$r[222]=array('iframe','d,w=\'\',h=\'\'','url width','iframe balise','builders');
$r[223]=array('eradic_acc','d','convert all accentuated  characters to normal','formated string','filters');
$r[224]=array('protect_utf','d','','','filters');
$r[225]=array('repair_latin','d','','','filters');
$r[226]=array('utf8_decode_b','d','','','filters');
$r[227]=array('html_entity_decode_b','v','','','filters');
$r[228]=array('unescape','d','convert entities like %u to ascii code (hex to dec)','ascii code','filters');
$r[229]=array('utflatindecode','d','convert recognized entities like %u to html code','decoded utflatin','filters');
$r[230]=array('urlutf','d,p','','','filters');
$r[231]=array('normalize','d','forbid special characters and accept only A-aZ-z0-9','formated string','filters');
$r[232]=array('entities','d','','','filters');
$r[233]=array('parse','v','','','filters');
$r[234]=array('strip_tags_b','d','','','filters');
$r[235]=array('clean_acc','v','kill all types of accents','formated string','filters');
$r[236]=array('clean_punct','in','apply typographic rules','formated string','filters');
$r[237]=array('clean_punct_b','v','apply typographic rules specific to bad spaces around the quote \" (slower)','formated string','filters');
$r[238]=array('lowercase','v','strtolower but keep ucfirst for each words','formated string','filters');
$r[239]=array('delbr','d,o','','','filters');
$r[240]=array('deln','d,o=\'\'','del /n','cleanup','filters');
$r[241]=array('delconn','d','','','filters');
$r[242]=array('embed_detect','v,s,e,n=\'\'','string start-cut end-cut cut_from','the part of $v who begin and finish with $s and $e','filters');
$r[243]=array('prop_detect','v,s','','','filters');
$r[244]=array('clean_title','d','','','filters');
$r[245]=array('scale_img','w,h,wo,ho,s','width height desired_width desired_height option (vertical priority =1)','part of make_mini','img');
$r[246]=array('make_mini','in,out,w,h,s','path desired_path width height option (vertical)','url of built miniature','img');
$r[247]=array('imgalpha','img','path','part of make_mini','img');
$r[248]=array('colors','d=\'\'','','','img');
$r[249]=array('rand_clr','','','','img');
$r[250]=array('hexrgb_r','d','','','img');
$r[251]=array('hexrgb','d,o=\'\'','hex2rgba','rgba()','img');
$r[252]=array('invert_color','p,o','','','img');
$r[253]=array('mails_list','','','','mails');
$r[254]=array('recup_mails_tosend','','','','mails');
$r[255]=array('prep_mail_html','suj,v,url','','','mails');
$r[256]=array('send_mail_html','dest,suj,v,from,url','','','mails');
$r[257]=array('send_mail_txt','dest,suj,v,from,url','','','mails');
$r[258]=array('send_mail','format,to,suj,msg,from,url','','','mails');
$r[259]=array('contact','t,c','','','mails');
$r[260]=array('stripslashes_b','d','','','php');
$r[261]=array('strin','v,s','','','php');
$r[262]=array('strchr_b','v,s','','','php');
$r[263]=array('strrchr_b','v,s','value separator','part of string after the separator, not including it','php');
$r[264]=array('substrpos','d,s','','','php');
$r[265]=array('substrrpos','d,s','','','php');
$r[266]=array('subtopos','ret,a,b','','','php');
$r[267]=array('split_r','d,n','data number','split at n position','php');
$r[268]=array('strprm','d,n=\'\',s=\'\'','','','php');
$r[269]=array('strdeb','v,s','','','php');
$r[270]=array('str_until','d,s','','','php');
$r[271]=array('split_one','s,v,n=\'\'','part of value after and before string (n=0), or after and before the last found string (n=1), let the sides a his place (right or left) if other is empty','an array with entries','php');
$r[272]=array('split_right','s,v,n=\'\'','','','php');
$r[273]=array('split_only','s,v,p=\'\',t=\'\'','','','php');
$r[274]=array('strsplit','v','php str_split() for php4','array of each letter of $v','php');
$r[275]=array('array_combine_a','a,b','a=keys b=values','combined array','php');
$r[276]=array('array_merge_b','r,rb','','','php');
$r[277]=array('array_merge_r','a,b','','','php');
$r[278]=array('array_unshift_b','&r,k,v','','','php');
$r[279]=array('array_reverse_b','r,s=\'\'','','','php');
$r[280]=array('array_keys_b','r','','','php');
$r[281]=array('array_keys_r','r,n,o=\'\'','r=array in an array n=range: key_target','array: values of a range','php');
$r[282]=array('in_array_b','va,r','find key in ranges r where value=va','like in_array() ','php');
$r[283]=array('in_array_r','r,d,n','array value number','verif if value exist in recursive array at column n','php');
$r[284]=array('array_add_r','ra,rb','add values to recursive arrays','new array','php');
$r[285]=array('array_walk_b','r,func,p1,p2','array function param2 param3','array of results of function apply to values of \'r\' as param1','php');
$r[286]=array('array_part','d,s,n','data split number','the occurrence \'n\' of the pattern \'d\' split with \'s\'','php');
$r[287]=array('walkeach','r,d,p','','','php');
$r[288]=array('unset_in','r,d,n','','','php');
$r[289]=array('array_push_after','ra,rb,p','','','php');
$r[290]=array('explode_r','d,a,b','','','php');
$r[291]=array('explode_k','d,a,b','','','php');
$r[292]=array('implode_k','r,a,b','','','php');
$r[293]=array('yesno','d','','','strings');
$r[294]=array('randid','p=\'\'','','','strings');
$r[295]=array('nchar','o,n','value number','same value n times (repetitive value)','strings');
$r[296]=array('splice','r,n','','','strings');
$r[297]=array('count_r','r','','','strings');
$r[298]=array('nearest','d,s','','','strings');
$r[299]=array('xt','v','give the strlower extension in v','formated string','strings');
$r[300]=array('xtb','v','give the strlower 4 last chars in v','formated string ','strings');
$r[301]=array('is_image','d','verify if doc is an image','true','strings');
$r[302]=array('determine_cond','cnd','','','strings');
$r[303]=array('rstr','n','value of restriction \'n\' (number)','no restriction return \'true\'','sessions');
$r[304]=array('auth','n','','','sessions');
$r[305]=array('prms','n','','','sessions');
$r[306]=array('prma','n','','','sessions');
$r[307]=array('prmb','n','','','sessions');
$r[308]=array('nms','d','number of the nomination','nominations (helps_nominations)','sessions');
$r[309]=array('yesnoses','d','','','sessions');
$r[310]=array('define_s','v,d','give the the session s the value d if session is not set, then give get value to session','value of the session $v','sessions');
$r[311]=array('getorpost','v,d','value data','post replace get, get replace data','sessions');
$r[312]=array('get','v','','','sessions');
$r[313]=array('geta','v,d','','','sessions');
$r[314]=array('post','d,v=\'\'','','','sessions');
$r[315]=array('ses','d,v=\'\'','call session from his name','value of session','sessions');
$r[316]=array('sesr','d,k,v=\'\'','','','sessions');
$r[317]=array('sesv','v,p=\'\',b=\'\'','','','sessions');
$r[318]=array('sesone','v,p=\'\'','','','sessions');
$r[319]=array('sesmk','v,p=\'\',b=\'\'','value_name function_name, reset','make session for datas (cache system)','sessions');
$r[320]=array('sesf','v,p=\'\',b=\'\'','','','sessions');
$r[321]=array('jc','','','','access');
$r[322]=array('root','','','','access');
$r[323]=array('prog','b=\'\',c=\'\'','','','access');
$r[324]=array('https','f','link','strip https','access');
$r[325]=array('http','f','','','access');
$r[326]=array('ishttp','f','','','access');
$r[327]=array('nohttp','f','','','access');
$r[328]=array('http_domain','f','','','access');
$r[329]=array('http_root','f','','','access');
$r[330]=array('findroot_b','u','','','access');
$r[331]=array('utmsrc','f','','','access');
$r[332]=array('host','','','','access');
$r[333]=array('htac','d','part of url knowing htaccess','the param of variable formated','access');
$r[334]=array('htacc','d','part of url knowing htaccess for \'read\' or \'id\'','the param of variable formated','access');
$r[335]=array('urlread','d','','','access');
$r[336]=array('philum','','','','access');
$r[337]=array('good_url','id,v','deprecated :: build explicit url from formated title (suj) if present, or i by default','url of an article found by htacc(\'read\')','access');
$r[338]=array('subdom','v','make url from hub v, depend if subdomain or htaccess are activated ','url','access');
$r[339]=array('prep_host','nod','good url with thttp for hub=nod if subdomain or htaccess or nothing activated','formated string','access');
$r[340]=array('hostname','','','','access');
$r[341]=array('mobile','','','','access');
$r[342]=array('feedproxy','f','','','access');
$r[343]=array('ajx','v,p=\'\'','','','ajax');
$r[344]=array('ajxr','res','','','ajax');
$r[345]=array('ajxg','d','','','ajax');
$r[346]=array('ajxp','res,pa,oa','','','ajax');
$r[347]=array('memtmp','','','','ajax');
$r[348]=array('core','f,p,v1,v2,v3,v4','','','ajax');
$r[349]=array('loadjs','f,d,t=\'\'','','','actions');
$r[350]=array('lj_tog','n,d,v','toggle button with content socket','','actions');
$r[351]=array('ljbub','v,lk,oc=\'\',ov=\'\',id=\'\',tg=\'\'','lj for bubbles','','actions');
$r[352]=array('saveiec','j,cat,rid,cid=\'\',v=\'\',x=\'\',c=\'\',suj=\'\'','used for save article','','actions');
$r[353]=array('btn_switch','d,g,l,v','session_name, indicator for true, link, text','button off/on with alert','actions');
$r[354]=array('plink','f','','','btns');
$r[355]=array('preplink','lk','link','root of link','btns');
$r[356]=array('prepdlink','val','','','btns');
$r[357]=array('nbof','n,i','number (count), numeber (value of nms)','plurial or signle of objects (nomination)','btns');
$r[358]=array('plurial','n,i','r=array of objects','letter \"s\" if $r>1','btns');
$r[359]=array('flags','','country','image flag of contry','btns');
$r[360]=array('flag','d','','','btns');
$r[361]=array('ascii','d,n=\'\'','d=ascii value, n=size','ascii code','btns');
$r[362]=array('svg','d','','','btns');
$r[363]=array('picto','d,p=\'\'','','','btns');
$r[364]=array('pictxt','p,t=\'\',s=\'\'','','','btns');
$r[365]=array('pictit','p,t,s=\'\'','','','btns');
$r[366]=array('imgico','f,t=\'\',h=\'\'','','image of icon','btns');
$r[367]=array('uicon','d,p,o=\'\'','','','btns');
$r[368]=array('icon','v,t=\'\',h=\'\',jc=\'\'','data directory','icon (image from icon/system by default)','btns');
$r[369]=array('ico','d,t=\'\'','','','btns');
$r[370]=array('callico','d,t=\'\',s=\'\',c=\'\'','','','btns');
$r[371]=array('icosys','d,s=\'\'','','','btns');
$r[372]=array('helps','d,nd=\'\'','key of helps_txts table','value of entry','btns');
$r[373]=array('hlpbt','j,t=\'\'','key of helps_txts table','button (?) opening help in a popup','btns');
$r[374]=array('msqlink','b,p,d=\'\',c=\'\'','','','btns');
$r[375]=array('tri_tag','v','','','btns');
$r[376]=array('tri_tags','r','','','btns');
$r[377]=array('compact_val','r,a,b','','','params');
$r[378]=array('decompact_conn','d','','','params');
$r[379]=array('decompact_conn_b','d','','','params');
$r[380]=array('decompact_mod','d','','','params');
$r[381]=array('subparams','d','','','params');
$r[382]=array('subparams_a','d','','','params');
$r[383]=array('good_param','d','','','params');
$r[384]=array('isplug','d','','','plug');
$r[385]=array('clplug_j','d,a=\'\',b=\'\'','','','plug');
$r[386]=array('call_func','c,r,v','css specific_array value','shortcut to lj() but params for SaveJ are in an array','plug');
$r[387]=array('call_plug_f','c,t,pl,f,p,v','','','plug');
$r[388]=array('call_plug','c,t,f,p,v','class target_div plug_name option value','shortcut to lj() specific for plugins (decide if prepare for popup)','plug');
$r[389]=array('plugin','d,p=\'\',o=\'\',ob=\'\',res=\'\'','plugin param1 param2','result of a plugin with params','plug');
$r[390]=array('plugin_func','d,f,p=\'\',o=\'\',res=\'\'','','','plug');
$r[391]=array('plug_core','d,p=\'\',o=\'\',res=\'\'','','','plug');
$r[392]=array('search_engine','d','','','plug');
$r[393]=array('call_finder','p,o','','','plug');
$r[394]=array('eye','p=\'\'','','','eye');
$r[395]=array('exc','d','','','utils');
$r[396]=array('req','d,j=\'\'','','','utils');
$r[397]=array('reqp','d','','','utils');
$r[398]=array('checkupdate','','','number of newest version of philum','utils');
$r[399]=array('checkversion','','','','utils');
$r[400]=array('utf','d','','','utils');
$r[401]=array('utfb','d','','','utils');
$r[402]=array('secure_inputs','','','','utils');
$r[403]=array('alert','d','','','utils');
$r[404]=array('patch_replace','bs,in,wh,repl','replace in by repl where wh in bs','confirmation success','utils');
$r[405]=array('currentwidth','','','','design');
$r[406]=array('curwidth_set','d','','','design');
$r[407]=array('active','d,n','','','design');
$r[408]=array('error_report','','','','design');
$r[409]=array('chrono','d','','','design');
$r[410]=array('pr','r','','','design');
$r[411]=array('window','d','','','design');
$r[412]=array('eco','d,o=\'\'','','','design');
$r[413]=array('verbose','r','','','design');

?>