<?php
//philum/microsql/program_core_sav
$r[1]=['p','r','print_r()','','html'];
$r[2]=['br','','','br balise','html'];
$r[3]=['hr','','','hr balise','html'];
$r[4]=['sep','','separator','','html'];
$r[5]=['atb','d,v','html attribut','d=\"v\"','html'];
$r[6]=['atc','d','class attribut','','html'];
$r[7]=['atd','d','id attribut','','html'];
$r[8]=['ats','d','style attribut','','html'];
$r[9]=['atn','d','name attribut','','html'];
$r[10]=['atv','d','value attribut','','html'];
$r[11]=['atz','d','size attribut','','html'];
$r[12]=['att','d','','','html'];
$r[13]=['atj','d,j','javascript prop and attribut','(\'j\');','html'];
$r[14]=['atjb','r','multiple javascript attributs','','html'];
$r[15]=['atjr','d,r','','','html'];
$r[16]=['sj','d','javascript function SaveJ','SaveJ(\'sj\');','html'];
$r[17]=['atbb','d','multiple attributs: class|id|style','','html'];
$r[18]=['atr','r','multiple props and attributs','','html'];
$r[19]=['ul','v','balise','embed content','html'];
$r[20]=['li','v','balise','embed content','html'];
$r[21]=['bal','b,v','b=balise v=value','balise html','html'];
$r[22]=['balc','b,c,v','balise class value','','html'];
$r[23]=['balb','b,p,v','balise, free manual props, value','','html'];
$r[24]=['balise','b,r,v','b=balise r=attributs t=text :: 
attributs_rule : use key instead of name of property :
array(1=>\"type\",2=>\"name\",3=>\"id\",4=>\"value\",5=>\"class\",6=>\"size\",7=>\"maxlenght\",8=>\"onKeyPress\",9=>\"cols\",10=>\"rows\",11=>\"wrap\",12=>\"action\",13=>\"method\",14=>\"for\",15=>\"onchange\",16=>\"style\")','html balise from an array of attributes','html'];
$r[25]=['span','p,v','free props, value','span balise','html'];
$r[26]=['btn','c,v','class text','span balise','html'];
$r[27]=['btd','d,v','id txt','span balise with id value','html'];
$r[28]=['bts','d,v','style value','span balise','html'];
$r[29]=['div','p,v','attributs value','div balise','html'];
$r[30]=['divr','p,v','','','html'];
$r[31]=['divb','p,v','class|is|style value','div balise','html'];
$r[32]=['divc','c,v','class value','div balise','html'];
$r[33]=['divd','d,v','id value','div balise','html'];
$r[34]=['divs','s,v','style text','div balise','html'];
$r[35]=['button','c,j,v','class javascript text','html button','html'];
$r[36]=['lk','u,p=\'\',v=\'\'','','','html'];
$r[37]=['lka','u,v=\'\'','link value','a balise, display domain only','html'];
$r[38]=['lkc','c,u,v','class link value','a balise','html'];
$r[39]=['lkt','c,u,v','class link value','a balise with target=_blank','html'];
$r[40]=['lkh','oc,ov,v,c=\'\'','onclick js, onhover js, value, class','a balise','html'];
$r[41]=['llk','c,l,v','class link value','a balise inside a li balise','html'];
$r[42]=['submitj','c,id,v','button javascript','button balise','html'];
$r[43]=['lja','c,j,v','','','html'];
$r[44]=['lj','c,j,v,o=\'\'','class js text','a balise with javascript function \'SaveJ\' - shortcut to lc()','html'];
$r[45]=['ljp','p,j,v','','','html'];
$r[46]=['ljb','c,p,j,v,a=\'\'','class, js function as attribut, js prop, value, 1=onmouseover else onclick','a balise with js and mouseover ability','html'];
$r[47]=['ljc','c,d,j,v,o=\'\',p=\'\'','js button calling a core function :
class, target, js, value, ajaxmode (3=display loading), \'p\' for popup','a balise','html'];
$r[48]=['ljh','c,j,v','on mouseover with timing and autoclose','a balise','html'];
$r[49]=['blj','c,id,j,v','using id as target for answer of ajax','a balise in span balise','html'];
$r[50]=['llj','c,j,v,id=\'\',a=\'\'','class, js, value, id of li, 1=mouseover','a balise in li balise','html'];
$r[51]=['image','d,w=\'\',h=\'\',p=\'\'','image width height props','html embed image','html'];
$r[52]=['img','d,s=\'\'','image at 100%','img balise','html'];
$r[53]=['rolloverimg','a,b','switch image on rollover','img button','html'];
$r[54]=['etc','d,n','cut text at n pos and add \"...\"','','html'];
$r[55]=['asciinb','n','','','html'];
$r[56]=['gridpos','d','','','html'];
$r[57]=['attr','r','','','html'];
$r[58]=['toggle','c,j,v,n=\'\'','class js text','toggle button with ajax call js_function','action_j'];
$r[59]=['bubble','c,ja,j,v','class js func, js prop, value','bubble button with ajax call js_function','action_j'];
$r[60]=['popbub','d,j,v,c=\'\',o=\'\'','call Apps from bubble','','action_j'];
$r[61]=['panup','d,j,v,c','','','action_j'];
$r[62]=['togbub','ja,j,v,c=\'\',o=\'\'','toggle bubble','','action_j'];
$r[63]=['togses','v,t','toggle session','tog button','action_j'];
$r[64]=['togses_j','d,t','','','action_j'];
$r[65]=['input','d,v,p=\'\'','type: 1,0 (text,hidden) or any input_type ; id value class','input text for forms','forms'];
$r[66]=['input0','t,d,v,p=\'\'','','','forms'];
$r[67]=['input1','d,v,s=\'\',c=\'\',h=\'\',m=\'\'','id value size class','input balise','forms'];
$r[68]=['input2','n,v,s=\'\',c=\'\',h=\'\',m=\'\',id=\'\'','type name value class','input text for forms','forms'];
$r[69]=['submit','n,v,c=\'\'','','','forms'];
$r[70]=['autoclic','n,v,sz,mx,c,h=\'\',o=\'\'','input text auto-hide content','balise input with javascript','forms'];
$r[71]=['jholder','v','old javascript holder','','forms'];
$r[72]=['hidden','n,d,v','name id value','input for forms ','forms'];
$r[73]=['checkbox','n,v,t,chk','chk=0/1 if checked','checkbox for a form','forms'];
$r[74]=['offon','d,t=\'\'','','picto true or false','forms'];
$r[75]=['checkbox_j','id,v,t=\'\',b=\'\',j=\'\'','','','forms'];
$r[76]=['checkact','id,v,t','','','forms'];
$r[77]=['label','id,c,s,t','id class style text','label balise connected to id_input (for=\"id\")','forms'];
$r[78]=['radiobtn','r,h,n','','','forms'];
$r[79]=['radioj','id,r,n','','','forms'];
$r[80]=['radiobtj','r,vrf,id,o=\'\'','','','forms'];
$r[81]=['txarea','id,v,cl,rw,p=\'\'','name text cols rows','text area','forms'];
$r[82]=['txareac_btns','','','','forms'];
$r[83]=['txareac','id,c,s,j,d,o=\'\'','','','forms'];
$r[84]=['divedit','id,c,s,j,d','','','forms'];
$r[85]=['txarea1','msg','msg, art or track (0/1), continue value (0/1)','textarea used for edit articles, callable from ajax','forms'];
$r[86]=['form','go,d','','','forms'];
$r[87]=['goodarea','id,v,n','jv=javascripts n=size or cols','balise input text or a textarea','forms'];
$r[88]=['upload_j','id,typ,o=\'\'','','','forms'];
$r[89]=['select','atr,r,kv,h=\'\'','','','forms'];
$r[90]=['header_html','','','','headers'];
$r[91]=['meta','d,v,c=\'\'','meta d=v and content=c','used by headers','headers'];
$r[92]=['css_link','d,m=\'\'','link to css','used by headers','headers'];
$r[93]=['js_link','d','js link','used by headers','headers'];
$r[94]=['css_code','d','css code','used by headers','headers'];
$r[95]=['js_code','d','js code','used by headers','headers'];
$r[96]=['temporize','name,func,p','name of the function, func=content, p=milliseconds :: temporize() will call a javascript cuntion every p seconds','javascript','headers'];
$r[97]=['relod','v','reload to a page','javascript immediately applied','headers'];
$r[98]=['header_tags','r','','','headers'];
$r[99]=['add','k,v','','','sessions'];
$r[100]=['get','d,v=\'\'','','','sessions'];
$r[101]=['generate','','','','headers'];
$r[102]=['connect','','','','mysql'];
$r[103]=['qd','d','','','mysql'];
$r[104]=['rcptb','db','show tables','mysql_query','mysql'];
$r[105]=['lstrc','rq','make array from range 0 in mysql_fetch_array','array','mysql'];
$r[106]=['qrr','r','','','mysql'];
$r[107]=['qra','r','','','mysql'];
$r[108]=['qrw','r','','','mysql'];
$r[109]=['qrf','r','','','mysql'];
$r[110]=['qrid','sql,o=\'\'','','','mysql'];
$r[111]=['qr','sql,o=\'\'','','','mysql'];
$r[112]=['qres','v','','','mysql'];
$r[113]=['atm','v','','','mysql'];
$r[114]=['atmr','r','','','mysql'];
$r[115]=['atmrup','r','','','mysql'];
$r[116]=['mysqlra','r,o','','','mysql'];
$r[117]=['mysqlrb','r,o','','','mysql'];
$r[118]=['insert','b,d,o=\'\'','','','mysql'];
$r[119]=['update','bs,set,v,col,id,o=\'\'','UPDATE bs SET in=v WHERE col=id','nothing (and no error)','mysql'];
$r[120]=['delete','bs,id,o=\'\'','delete in bs where id','nothing','mysql'];
$r[121]=['reflush','bs,o=\'\'','ALTER TABLE bs ORDER BY id :: used by delete()','nothing','mysql'];
$r[122]=['lastid','bs','sql command','id of most recent entry','mysql'];
$r[123]=['sqlformat','rq,p','','','mysql'];
$r[124]=['sql','d,b,p,q,z=\'\'','','','mysql'];
$r[125]=['sqb','d,b,p,q,z=\'\'','','','mysql'];
$r[126]=['sqr','d,b,q=\'\',z=\'\'','','','mysql'];
$r[127]=['sql_inner','d,b1,b2,key,p,q,z=\'\'','','','mysql'];
$r[128]=['sql_b','sql,p,z=\'\'','','','mysql'];
$r[129]=['mkdir_r','u','build directories topology from a string like dir1/dir11/dir111','nothing','dirs'];
$r[130]=['rmdir_r','dr','path dir file topo_number','delete files of a directory, including other dirs ;
option of explode_dir function (used inside a routine)','dirs'];
$r[131]=['explore','dr,p=\'\',o=\'\'','','','dirs'];
$r[132]=['explode_dir','r,d,func','used after explore() in obtain_from_dir()','array of files in $j directory applied to the function $func','dirs'];
$r[133]=['func','d,k,f,n','it\'s an example of func() used  by explode_dir()','string for array built by explode_dir()','dirs'];
$r[134]=['walk_dir','dr,func','','','dirs'];
$r[135]=['read_file','f','open datas from fil f','text','files'];
$r[136]=['write_file','f,t','file_url text to save in f','save file on server','files'];
$r[137]=['get_file','f','','','files'];
$r[138]=['file_get_context','f','','','files'];
$r[139]=['curl_get_contents','f,post=\'\'','','','files'];
$r[140]=['joinable','d','','','files'];
$r[141]=['recup_fileinfo','doc','file','formated date and size of a file','files'];
$r[142]=['ftime','f,d=\'\'','file','formated date of a file ','files'];
$r[143]=['fsize','f','file','formated size of a file ','files'];
$r[144]=['fwidth','f','','','files'];
$r[145]=['frdate','d','','','files'];
$r[146]=['localdate','d','','','files'];
$r[147]=['gz_create','f,fb','file_url bz_name of the compressed archive','store a bz archive','files'];
$r[148]=['gz_read','f','','','files'];
$r[149]=['gz_write','d,f','bz_url file_name of the decompressed archive','store a file from a bz archive','files'];
$r[150]=['gz2im','f','','','files'];
$r[151]=['is_zip','f','','','files'];
$r[152]=['unpack_gz','f,d','','','files'];
$r[153]=['db_f','nod,dr=\'usr/\'','','','db'];
$r[154]=['db_init','f','','','db'];
$r[155]=['db_add','f,row','','','db'];
$r[156]=['db_write','f,r','','','db'];
$r[157]=['db_read','f','','','db'];
$r[158]=['nod','d','','','microsql'];
$r[159]=['dump','r,p','array of arrays and name of node like \'hub_table\'','prepared values for create_page()','microsql'];
$r[160]=['msq_patch','f,r,nod','','','microsql'];
$r[161]=['msq_menus','r','','','microsql'];
$r[162]=['read_vars','dr,nod,defsb','','','microsql'];
$r[163]=['save_vars','dr,nod,r','save microtable: directory table defs=array of arrays','nothing','microsql'];
$r[164]=['msql_save','dr,nod,r,h=\'\'','save array of arrays defs in base/nod adding dfb as _menus_  :: resolve root problems','nothing','microsql'];
$r[165]=['msql_displace','dr,nod,id,to','','','microsql'];
$r[166]=['modif_vars','dr,nod,ra,d,dfb=\'\'','  (like hub_table) =array of arrays =\'add\' / \'push\' / \'del\' / value (optionnal)','the modified microtable with $arr','microsql'];
$r[167]=['msql_modif','dr,nod,defs,dfb,act,n','dir node definitions menus action value 
Actions are : 
(defs is a value of a range) :
- one : modif value n
- push : add one value
(defs is the entire table) :
- arr : replace the array 
- mdf : replace value present in defs
- del : deleted values present in defs
- add : add values of defs ; if n=\'mdf\' verif if value already exists before to add it','saved array','microsql'];
$r[168]=['msql_read','dr,nod,in=\'\',u=\'\'','directory nod=table i=range (optionnal) :: resolve root problems','array of a table 
or a part of it 
or only the value there is only one range','microsql'];
$r[169]=['msql_read_b','dr,nod,in=\'\',u=\'\',ra=\'\'','','','microsql'];
$r[170]=['msq_create','d,r,rb,k','','','microsql'];
$r[171]=['msq_where','dr,nod,n,d,o=\'\'','','','microsql'];
$r[172]=['msq_choose','dr,pr,nd','','','microsql'];
$r[173]=['msq_find_last','dr,pr,nod','directory hub table','previous empty value to fill (1,2,4 existing return 3)','microsql'];
$r[174]=['msq_next_table','r','','','microsql'];
$r[175]=['msq_next_entry','r','','','microsql'];
$r[176]=['msq_goodtable','d','value of a table designed by string command as \'base/node§key\' in a connector ; abble to decide if the key is a number of table or a key of one table','table','microsql'];
$r[177]=['msql_read_prep','b,d','','','microsql'];
$r[178]=['msq_format','r','','','microsql'];
$r[179]=['msq_col','r,n','','','microsql'];
$r[180]=['msq_cat','r,n','array number','make a list form the column of a table (unique key)','microsql'];
$r[181]=['msq_tri','r,n,vrf','array, number, verif','return the values of a column of a table','microsql'];
$r[182]=['msq_sort','r,n,i','','','microsql'];
$r[183]=['msq_reorder','r','reorder the key of a table, beginning from 1','array','microsql'];
$r[184]=['msq_move','r,ka,va','','','microsql'];
$r[185]=['msq_displace','r,id,to','','','microsql'];
$r[186]=['msq_walk','r,n,func,p','array, number, function, param','apply a function with param to each value of a column n','microsql'];
$r[187]=['msq_walk_k','r,func','array, function','apply a function to the keys','microsql'];
$r[188]=['msq_prep','r','affect numeric keys to a table, from 1','table with numerical keys','microsql'];
$r[189]=['msq_prevnext','r,d','','','microsql'];
$r[190]=['msq_copy','da,na,db,nb','','','microsql'];
$r[191]=['msq_n','dr,nod,d','','','microsql'];
$r[192]=['msq_append','defs,d','','','microsql'];
$r[193]=['msq_merge','r,dr,nd','','','microsql'];
$r[194]=['msq_ses','v,dr,nod,u','','','microsql'];
$r[195]=['msq_data','d,o=\'\'','','','microsql'];
$r[196]=['msq_f','dr,nod','','','microsql'];
$r[197]=['make_table','r,head=\'\',keys=\'\'','datas=array of arrays, csb is only for the first range','balise table','tables'];
$r[198]=['make_divtable','r,h=\'\'','','','tables'];
$r[199]=['make_tables','rt,r,csa,csb,o=\'\'','datas=array of arrays, csb is only for the first range, if it is present in titles','balise table','tables'];
$r[200]=['array_conn','r','','','tables'];
$r[201]=['make_tabs','r,ud=\'\',c=\'\'','array with keys used as tabs','html javascript tabs','tables'];
$r[202]=['slct_menus','r,lk,vf,cs1,cs2,kv','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cs1=active cs2=normal css kv=k or v: use key or value','list of links with detection of activated ','menus'];
$r[203]=['slct_menus_tags','r,lk,vf,ct,csa,kv','r=array lk=link (like /?var=) vf=verif (var) ct=if nb is called, render also the number of occurences) cs1=css (use active class if detect var) kv=k/v: use key or value','list of links under li balise with detection of activated ','menus'];
$r[204]=['slctmenusj','r,j,vf,sep,kv=\'\'','r=array (keys will be used) lk=link (like /?var=) vf=verif (var) cal=javascript to call','list of links in javascript with detection of selected','menus'];
$r[205]=['slctmenusja','r,j,vf','','','menus'];
$r[206]=['slctmenus_sj','r,go,vf','array, js_command for SaveJ, active value (verif)','list of links calling ajax (SaveJ) with string VAR in js_command replaced by the key of each array','menus'];
$r[207]=['jump_btns','id,v,add,c=\'\'','buttons of values separated by \"|\" in v sent by javascript to id and replacing the input id if add=0 or adding the words in add (like \', \')','buttons who send values in an input','menus'];
$r[208]=['menuder_h','r,id,d,j','','','menus'];
$r[209]=['menuderj_prep','pr,id,t,opt=\'\'','','','menus'];
$r[210]=['mkbub','d,c=\'\',s=\'\',o=\'\'','','','menus'];
$r[211]=['bubslct','j,t','','','menus'];
$r[212]=['select_jp','id,f,v=\'\',o=\'\',t=\'\'','','','menus'];
$r[213]=['select_jb','id,pr,v=\'\',o=\'\',oj=\'\'','','','menus'];
$r[214]=['select_j','id,f,v=\'\',o=\'\',t=\'\',ty=\'\'','','','select_j //existing_list'];
$r[215]=['msql_slct','id,k,murl','','','select_j //existing_list'];
$r[216]=['read_rss_data','data,t,r','','','rss'];
$r[217]=['read_rss','f,t,r','system/program_functions.php=file_url =master_balise name (like \'item\') =array of sub-balises (like \'title\',\'description\')','array of arrays of an sml or rss source','rss'];
$r[218]=['read_xml','f','','','rss'];
$r[219]=['load_xml','f,o=\'\'','','','rss'];
$r[220]=['mkdts','','','','rss'];
$r[221]=['rss_date','date','find timestamp from rss formated date','timestamp','rss'];
$r[222]=['rss_time','date','','','rss'];
$r[223]=['mkday','d=\'\',p=\'\'','timestamp','datadav using \'ymd\'','dates'];
$r[224]=['calc_date','d','d=timestamp','timestamp of $d days before','dates'];
$r[225]=['calctime','d','','','dates'];
$r[226]=['mtime','','','','dates'];
$r[227]=['timelang','','','','dates'];
$r[228]=['time_prev','d','','','dates'];
$r[229]=['time_ago','dt','php date(dt,df=timestamp) use relative time','formated string like \'2h 10min ago\'','dates'];
$r[230]=['timetravel','','','','dates'];
$r[231]=['on2cols','r,w,p','r is an array with key=label and value=content, w=total width, with of labels=1/p','table in divs','builders'];
$r[232]=['onxcols','re,prm,w,h=\'\'','','','builders'];
$r[233]=['scroll','r,d,n,w=\'\',h=\'\',id=\'\'','obj=array used to build txt, nb is the limit for create a scrool','div with ovrflow if needed','builders'];
$r[234]=['scroll_b','r,d,n,w=\'\',h=\'\',id=\'\'','','','builders'];
$r[235]=['iframe','d,w=\'\',h=\'\'','url width','iframe balise','builders'];
$r[236]=['video_html','f,w=\'\',h=\'\'','','','builders'];
$r[237]=['eradic_acc','d','convert all accentuated  characters to normal','formated string','filters'];
$r[238]=['protect_utf','d','','','filters'];
$r[239]=['repair_latin','d','','','filters'];
$r[240]=['utf8_decode_a','d','','','filters'];
$r[241]=['utf8_decode_b','d','','','filters'];
$r[242]=['html_entity_decode_b','v','','','filters'];
$r[243]=['specialspace','d','','','filters'];
$r[244]=['decode_unicode','d','','','filters'];
$r[245]=['utflatindecode','d','convert recognized entities like %u to html code','decoded utflatin','filters'];
$r[246]=['urlutf','d,p','','','filters'];
$r[247]=['normalize','d','forbid special characters and accept only A-aZ-z0-9','formated string','filters'];
$r[248]=['entities','d','','','filters'];
$r[249]=['parse','v','','','filters'];
$r[250]=['strip_tags_b','d','','','filters'];
$r[251]=['clean_acc','v','kill all types of accents','formated string','filters'];
$r[252]=['clean_punct','in','apply typographic rules','formated string','filters'];
$r[253]=['clean_punct_b','v','apply typographic rules specific to bad spaces around the quote \" (slower)','formated string','filters'];
$r[254]=['lowercase','v','strtolower but keep ucfirst for each words','formated string','filters'];
$r[255]=['delbr','d,o','','','filters'];
$r[256]=['deln','d,o=\'\'','del /n','cleanup','filters'];
$r[257]=['delconn','d','','','filters'];
$r[258]=['embed_detect','v,s,e,n=\'\'','string start-cut end-cut cut_from','the part of $v who begin and finish with $s and $e','filters'];
$r[259]=['prop_detect','v,s','','','filters'];
$r[260]=['clean_title','d','','','filters'];
$r[261]=['scale_img','w,h,wo,ho,s','width height desired_width desired_height option (vertical priority =1)','part of make_mini','img'];
$r[262]=['make_mini','in,out,w,h,s','path desired_path width height option (vertical)','url of built miniature','img'];
$r[263]=['imgalpha','img','path','part of make_mini','img'];
$r[264]=['colors','d=\'\'','','','img'];
$r[265]=['rand_clr','','','','img'];
$r[266]=['hexrgb_r','d','','','img'];
$r[267]=['hexrgb','d,o=\'\'','hex2rgba','rgba()','img'];
$r[268]=['invert_color','p,o','','','img'];
$r[269]=['prep_mail_html','suj,v,url','','','mails'];
$r[270]=['send_mail_html','dest,suj,v,from,url','','','mails'];
$r[271]=['send_mail_txt','dest,suj,v,from,url','','','mails'];
$r[272]=['send_mail','format,to,suj,msg,from,url','','','mails'];
$r[273]=['contact','t,c','','','mails'];
$r[274]=['stripslashes_b','d','','','php'];
$r[275]=['strin','v,s','','','php'];
$r[276]=['strchr_b','v,s','','','php'];
$r[277]=['strrchr_b','v,s','value separator','part of string after the separator, not including it','php'];
$r[278]=['substrpos','d,s','','','php'];
$r[279]=['substrrpos','d,s','','','php'];
$r[280]=['subtopos','ret,a,b','','','php'];
$r[281]=['split_r','d,n','data number','split at n position','php'];
$r[282]=['strprm','d,n=\'\',s=\'\'','','','php'];
$r[283]=['strdeb','v,s','','','php'];
$r[284]=['strend','v,s','','','php'];
$r[285]=['str_until','d,s','','','php'];
$r[286]=['split_one','s,v,n=\'\'','part of value after and before string (n=0), or after and before the last found string (n=1), let the sides a his place (right or left) if other is empty','an array with entries','php'];
$r[287]=['split_right','s,v,n=\'\'','','','php'];
$r[288]=['str_extract','s,v,p=\'\',t=\'\'','','','php'];
$r[289]=['strsplit','v','php str_split() for php4','array of each letter of $v','php'];
$r[290]=['array_combine_a','a,b','a=keys b=values','combined array','php'];
$r[291]=['array_combine_sub','a,b','','','php'];
$r[292]=['array_merge_b','r,rb','','','php'];
$r[293]=['array_merge_r','a,b','','','php'];
$r[294]=['array_unshift_b','&r,k,v','','','php'];
$r[295]=['array_reverse_b','r,s=\'\'','','','php'];
$r[296]=['array_keys_b','r','','','php'];
$r[297]=['array_keys_r','r,n,o=\'\'','r=array in an array n=range: key_target','array: values of a range','php'];
$r[298]=['in_array_b','d,r','find key in ranges r where value=va','like in_array() ','php'];
$r[299]=['in_array_p','d,r','','','php'];
$r[300]=['in_array_r','r,d,n','array value number','verif if value exist in recursive array at column n','php'];
$r[301]=['array_add_r','ra,rb','add values to recursive arrays','new array','php'];
$r[302]=['array_walk_b','r,func,p1,p2','array function param2 param3','array of results of function apply to values of \'r\' as param1','php'];
$r[303]=['array_part','d,s,n','data split number','the occurrence \'n\' of the pattern \'d\' split with \'s\'','php'];
$r[304]=['walkeach','r,d,p','','','php'];
$r[305]=['unset_in','r,d,n','','','php'];
$r[306]=['array_push_after','ra,rb,p','','','php'];
$r[307]=['explode_r','d,a,b','','','php'];
$r[308]=['explode_k','d,a,b','','','php'];
$r[309]=['implode_k','r,a,b','','','php'];
$r[310]=['implode_keys','r,a=\'\'','','','php'];
$r[311]=['yesno','d','','','strings'];
$r[312]=['randid','p=\'\'','','','strings'];
$r[313]=['nchar','o,n','value number','same value n times (repetitive value)','strings'];
$r[314]=['splice','r,n','','','strings'];
$r[315]=['count_r','r','','','strings'];
$r[316]=['nearest','d,s','','','strings'];
$r[317]=['xt','d','give the strlower extension in v','formated string','strings'];
$r[318]=['xtb','d','give the strlower 4 last chars in v','formated string ','strings'];
$r[319]=['is_image','d','verify if doc is an image','true','strings'];
$r[320]=['determine_cond','cnd','','','context'];
$r[321]=['define_modc_b','vl','','','context'];
$r[322]=['rstr','n','value of restriction \'n\' (number)','no restriction return \'true\'','sessions'];
$r[323]=['auth','n','','','sessions'];
$r[324]=['prms','n','','','sessions'];
$r[325]=['prma','n','','','sessions'];
$r[326]=['prmb','n','','','sessions'];
$r[327]=['nms','d','number of the nomination','nominations (helps_nominations)','sessions'];
$r[328]=['yesnoses','d','','','sessions'];
$r[329]=['msqlang','d','','','sessions'];
$r[330]=['voc','d,b','','','sessions'];
$r[331]=['getif','v,d','','','sessions'];
$r[332]=['geta','d,v','','','sessions'];
$r[333]=['post','d,v=\'\'','','','sessions'];
$r[334]=['ses','d,v=\'\'','call session from his name','value of session','sessions'];
$r[335]=['sesz','d,v=\'\'','','','sessions'];
$r[336]=['sesg','v,d','','','sessions'];
$r[337]=['sesr','d,k,v=\'\'','','','sessions'];
$r[338]=['sesif','d,v=\'\'','','','sessions'];
$r[339]=['sesone','v,p=\'\'','','','sessions'];
$r[340]=['sesmk','v,p=\'\',b=\'\'','value_name function_name, reset','make session for datas (cache system)','sessions'];
$r[341]=['jc','','','','access'];
$r[342]=['root','','','','access'];
$r[343]=['prog','o=\'\'','','','access'];
$r[344]=['progb','o=\'\'','','','access'];
$r[345]=['https','f','link','strip https','access'];
$r[346]=['http','f','','','access'];
$r[347]=['ishttp','f','','','access'];
$r[348]=['nohttp','f','','','access'];
$r[349]=['http_domain','f','','','access'];
$r[350]=['http_root','f','','','access'];
$r[351]=['findroot_b','u','','','access'];
$r[352]=['utmsrc','f','','','access'];
$r[353]=['host','','','','access'];
$r[354]=['htac','d','part of url knowing htaccess','the param of variable formated','access'];
$r[355]=['htacc','d','part of url knowing htaccess for \'read\' or \'id\'','the param of variable formated','access'];
$r[356]=['urlread','d','','','access'];
$r[357]=['philum','','','','access'];
$r[358]=['good_url','id,v','deprecated :: build explicit url from formated title (suj) if present, or i by default','url of an article found by htacc(\'read\')','access'];
$r[359]=['subdom','v','make url from hub v, depend if subdomain or htaccess are activated ','url','access'];
$r[360]=['prep_host','nod','good url with thttp for hub=nod if subdomain or htaccess or nothing activated','formated string','access'];
$r[361]=['hostname','','','','access'];
$r[362]=['mobile','','','','access'];
$r[363]=['hardurl','d','','','access'];
$r[364]=['feedproxy','f','','','access'];
$r[365]=['ajx','v,p=\'\'','','','ajax'];
$r[366]=['ajxg','d','','','ajax'];
$r[367]=['ajxr','res','','','ajax'];
$r[368]=['ajxp','res,pa,oa','','','ajax'];
$r[369]=['memtmp','','','','ajax'];
$r[370]=['loadjs','f,d,t=\'\'','','','actions'];
$r[371]=['lj_tog','n,d,v','toggle button with content socket','','actions'];
$r[372]=['ljbub','v,lk,oc=\'\',ov=\'\',id=\'\',tg=\'\'','lj for bubbles','','actions'];
$r[373]=['saveiec','j,cat,rid,cid=\'\',v=\'\',x=\'\',c=\'\',suj=\'\'','used for save article','','actions'];
$r[374]=['btn_switch','d,g,l,v','session_name, indicator for true, link, text','button off/on with alert','actions'];
$r[375]=['preplink','lk','link','root of link','btns'];
$r[376]=['prepdlink','val','','','btns'];
$r[377]=['nbof','n,i','number (count), numeber (value of nms)','plurial or signle of objects (nomination)','btns'];
$r[378]=['plurial','n,i','r=array of objects','letter \"s\" if $r>1','btns'];
$r[379]=['flags','','country','image flag of contry','btns'];
$r[380]=['flag','d','','','btns'];
$r[381]=['ascii','d,n=\'\'','d=ascii value, n=size','ascii code','btns'];
$r[382]=['svg','d','','','btns'];
$r[383]=['picto','d,s=\'\',c=\'\'','','','btns'];
$r[384]=['pictxt','p,t=\'\',s=\'\'','','','btns'];
$r[385]=['pictit','p,t,s=\'\'','','','btns'];
$r[386]=['imgico','f,t=\'\',h=\'\'','','image of icon','btns'];
$r[387]=['uicon','d,p,o=\'\'','','','btns'];
$r[388]=['icon','v,t=\'\',h=\'\',jc=\'\'','data directory','icon (image from icon/system by default)','btns'];
$r[389]=['ico','d,t=\'\'','','','btns'];
$r[390]=['icons_r','','','','btns'];
$r[391]=['callico','d,t=\'\',s=\'\',c=\'\'','','','btns'];
$r[392]=['icosys','d,s=\'\'','','','btns'];
$r[393]=['helps','d,nd=\'\'','key of helps_txts table','value of entry','btns'];
$r[394]=['hlpbt','j,t=\'\'','key of helps_txts table','button (?) opening help in a popup','btns'];
$r[395]=['msqlink','b,p,d=\'\',c=\'\'','','','btns'];
$r[396]=['tri_tag','v','','','btns'];
$r[397]=['compact_val','r,a,b','','','params'];
$r[398]=['decompact_conn','d','','','params'];
$r[399]=['decompact_conn_b','d','','','params'];
$r[400]=['decompact_mod','d','','','params'];
$r[401]=['subparams','d','','','params'];
$r[402]=['subparams_a','d','','','params'];
$r[403]=['good_param','d','','','params'];
$r[404]=['clplug_j','d,a=\'\',b=\'\'','','','plug'];
$r[405]=['call_func','c,r,v','css specific_array value','shortcut to lj() but params for SaveJ are in an array','plug'];
$r[406]=['call_plug','c,t,f,p,v','class target_div plug_name option value','shortcut to lj() specific for plugins (decide if prepare for popup)','plug'];
$r[407]=['plugin','d,p=\'\',o=\'\',ob=\'\',res=\'\'','plugin param1 param2','result of a plugin with params','plug'];
$r[408]=['plugin_func','d,fc,p=\'\',o=\'\',res=\'\'','','','plug'];
$r[409]=['appin','d,mth,p=\'\',o=\'\'','','','plug'];
$r[410]=['search_engine','d','','','plug'];
$r[411]=['call_finder','p,o','','','plug'];
$r[412]=['eye','p=\'\'','','','eye'];
$r[413]=['exc','d','','','utils'];
$r[414]=['req','d,j=\'\'','','','utils'];
$r[415]=['scanplug','','','','utils'];
$r[416]=['reqp','d','','','utils'];
$r[417]=['checkupdate','','','number of newest version of philum','utils'];
$r[418]=['checkversion','','','','utils'];
$r[419]=['utf','d','','','utils'];
$r[420]=['utfb','d','','','utils'];
$r[421]=['utfc','d','','','utils'];
$r[422]=['secure_inputs','','','','utils'];
$r[423]=['genpswd','nb=8','','','utils'];
$r[424]=['alert','d','','','utils'];
$r[425]=['patch_replace','bs,in,wh,repl','replace in by repl where wh in bs','confirmation success','utils'];
$r[426]=['currentwidth','','','','design'];
$r[427]=['curwidth_set','d','','','design'];
$r[428]=['active','d,n','','','design'];
$r[429]=['error_report','','','','design'];
$r[430]=['chrono','d=\'\'','','','design'];
$r[431]=['pr','r','','','design'];
$r[432]=['window','d','','','design'];
$r[433]=['eco','d,o=\'\'','','','design'];
$r[434]=['verbose','r','','','design'];
$r["_menus_"]=['function','variables','usage','return','context'];

?>