<?php //msql/program_dev
$r=["1424184835"=>['progb','finder','share_file','function share_file($d,$p,$b){$mnu[\'_menus_\']=array(\'url\',\'vurl\');
$_SESSION[\'curdir\']=msql_modif(\'users\',$_SESSION[\'qb\'].\'_shared\',array($d,$p),$mnu,$b,$b==\'del\'?$p:0); distrib_share();'],
"1424184937"=>['progb','finder','share_file','function share_file($d,$p,$b){$mnu[\'_menus_\']=array(\'url\',\'vurl\');
$_SESSION[\'curdir\']=msql_modif(\'users\',$_SESSION[\'qb\'].\'_shared\',array($d,$p),$mnu,$b,$b==\'del\'?$p:0); distrib_share();'],
"1424185070"=>['progb','finder','share_file','function share_file($d,$p,$b){$mnu[\'_menus_\']=array(\'url\',\'vurl\');
$_SESSION[\'curdir\']=msql_modif(\'users\',$_SESSION[\'qb\'].\'_shared\',array($d,$p),$mnu,$b,$b==\'del\'?$p:0); distrib_share();'],
"1424185105"=>['progb','finder','share_file','function share_file($d,$p,$b){$mnu[\'_menus_\']=array(\'url\',\'vurl\');
$_SESSION[\'curdir\']=msql_modif(\'users\',$_SESSION[\'qb\'].\'_shared\',array($d,$p),$mnu,$b,$b==\'del\'?$p:0); distrib_share();'],
"1424185130"=>['progb','finder','share_file','function share_file($d,$p,$b){$mnu[\'_menus_\']=array(\'url\',\'vurl\');
$_SESSION[\'curdir\']=msql_modif(\'users\',$_SESSION[\'qb\'].\'_shared\',array($d,$p),$mnu,$b,$b==\'del\'?$p:0); distrib_share();']];