<?php //philum/microsql/connectors_all
$r=["_menus_"=>['description'],"h"=>['h3'],"b"=>['gras'],"i"=>['italique'],"u"=>['souligné'],"q"=>['bloc'],"s"=>['stabilo'],"r"=>['red'],"c"=>['css \'txtclr\' (couleur)'],"k"=>['barré'],"l"=>['petite taille'],"e"=>['exposant'],"pre"=>['balise \'pre\' (preformated) améliorée'],"code"=>['balise code'],"php"=>['affiche du code php avec sa coloration syntaxique'],"color"=>['couleur du texte : [text§dd0000:color] [text§indigo:color]'],"cols"=>['met le contenu dans des colonnes : [§3:cols] (nombre), [§300:cols] (taille en px)'],"block"=>['met le contenu dans un block : [§3:block] (%), [§300:block] (taille en px)'],":(all)"=>[''],":b"=>['efface les connecteurs :b'],":c"=>['efface les connecteurs :c'],":h"=>['efface les connecteurs :h'],":h2"=>['efface les connecteurs :h2'],":i"=>['efface les connecteurs :i'],":list"=>['efface les connecteurs :list'],":no"=>['efface les connecteurs :no'],":q"=>['efface les connecteurs :q'],":s"=>['efface les connecteurs :s'],":u"=>['efface les connecteurs :u'],":(any)"=>[''],"add_lines"=>['ajoute des lignes à la fin de chaque phrase'],"ajax"=>['bouton qui renvoie sur place (ou dans un div cible) le résultat d\'un module ou d\'un connecteur.

syntaxe : 
 [param/title/command/option:module->target§button[,]:ajax] 
où : 
- param/title/command/option:module ; 
- target = div cible ; 
- button = à afficher ;

La séquence peut être répétée en utilisant la virgule comme séparateur, de façon à produire un menu.

essayer : [id:read§screen:ajax] qui renvoie un contenu d\'article.'],"ajxget"=>['outil de préservation des caractères \':\', \'/\' et \'§\' pour le connecteur \'module\''],"apps"=>['appelle une Apps, 
- en référence à celles du module système : [6:apps][6§hello:apps]
- ou écrite à la volée : [button;plug;stext:apps]
syntaxe(bouton;type;process;param;option)'],"articles"=>['liste d\'articles d\'après un tri, avec nombreux modes de présentation'],"basic"=>['exécute le code d\'instructions codeline basic'],"bkg"=>['image en background : [value§img:bkg] (la première du catalogue par défaut)'],"book"=>['relie des articles en un livre'],"bubble"=>['menu à tiroirs en ajax (syntaxe du module \'submenus\')'],"chat"=>['module de Chat en Ajax'],"clean_br"=>['interdit plus de deux sauts de lignes'],"clean_mail"=>['retire les sauts de ligne illégaux'],"striplink"=>[''],"clear"=>['annule détourage image'],"console"=>['classe css \'console\''],"convert_html"=>['convertit le html en connecteurs'],"css"=>['applique un css au texte sélectionné'],"data"=>['données affiliées à l\'article (son id). 
hello§1:msq_data va écrire hello à la ligne 1, 
réécrire le connecteur en 1:msq_data, 
pour afficher la valeur associée à la clef 1'],"download"=>['pointe vers un fichier et l\'envoie à l\'utilisateur'],"draw"=>['apli externe'],"easy_tables"=>['éclairci les tableaux'],"font"=>['typo du texte [pHilUM§microsys:font]'],"footnotes"=>['ajoute des ancres si (1) ou [1] est détecté deux fois'],"formail"=>['formulaire d\'envoi de message'],"forum"=>['place un module de Forum'],"h1"=>['balise h1 (très grand texte)'],"h2"=>['balise h2 (grand texte)'],"header"=>['renvoie du contenu dans le header'],"html"=>['[pHilUM§css=txtcadr size=16 font=microsys color=firebrick:html]'],"iframe"=>['renvoie une \'iframe\' d\'un lien html : [src§width/height/name/seamless:iframe]'],"img"=>['force à considérer ce lien comme une image'],"img_label"=>['tente de trouver si un texte est le commentaire d\'image'],"imgtxt"=>['typos GDF ([text§typo:imgtxt]'],"import"=>['importe un article depuis son Url'],"jconn"=>['appelle un connecteur sur place en ajax : [248:read§open:jconn]'],"jopen"=>['ouvre un contenu sur place en ajax : [ID:jopen]'],"jukebox"=>['lecteur des mp3 d\'un répertoire [hub/dossier:jukebox]'],"last-update"=>['date de la dernière modification d\'un document'],"last_saved"=>['revient à la dernière action d\'enregistrement'],"lines"=>['efface les sauts de ligne du texte sélectionné'],"link"=>['liens prédéfinis :
- lien-clef : Home, ID, catégorie, module
- mettre un titre : Home§Accueil
- utiliser un picto : Home§home:picto
- lien interne : /?plug=myplug§name_of_plug'],"list"=>['liste'],"lowcase"=>['réduit la casse (minuscules) du texte sélectionné'],"msq_form"=>['confère au visiteur le moyen d\'ajouter des entrées dans une table msql ; exemple de formulaire à mettre en paramètre : date=date, choix1/choix2=list, entrée1, entrée2, message=text, image=upload, mail=mail, ok=button'],"msq_read"=>['place les données d\'une table msql dans un template.
ex: [dev_ads_353§readatas:microread]
- fabriquer des données avec :microform,
- fabriquer des templates dans admin/templates'],"msql"=>['renvoie les données d\'une table : 
[hub_table_(version)-(key)|(row)§option:microsql] ;'],"mini"=>['fabrique une miniature d\'une image avec des dimensions personnalisées : [img.jpg§140/100:mini]
+ lien vers l\'original dans une popup en ajax'],"module"=>['affiche un ou des modules - séparés par une barre verticale (|) ; ex: [hour|Home:link:module] (voir constructeurs / modules)'],"msq_bin"=>['convertit les 1 et 0 des données d\'une base microsql en images explicites'],"msq_conn"=>['comme :microsql mais interprète les connecteurs dans les données'],"msq_count"=>['renvoie le nombre de lignes d\'une base microsql'],"msq_graph"=>['renvoie un histogramme des données d\'une colonne ou d\'une ligne d\'une table microsql ; ex: [node_base§col:msq_graph] (colonne) [node_base_key:msq_graph] (ligne)'],"msq_lasts"=>['[node§10:msq_lasts] renvoie les 10 derniers éléments du tableau'],"no"=>['n\'affiche pas le contenu'],"numlist"=>['liste numérotées (pour chaque saut de ligne)'],"old_conn"=>['réécrit les connecteurs obsolètes'],"on"=>['affiche le connecteur [hello:b:on]'],"p"=>['balise p (paragraphe)'],"paste"=>['coller du html et récupérer des connecteurs'],"pdf"=>['lecteur PDF ; ex: doc:pdf'],"petition"=>['pétition en ligne'],"photo"=>['geleries photo'],"plug"=>['connecteur imbriqué : [param§option:plugin:plug]'],"plup"=>['plugin dans une popup 
[param§option:plugin§button:plup]'],"figure"=>['[image.jpg§texte:figure]'],"pop"=>['ouvre le contenu dans une popup [texte§titre:pop]'],"popart"=>['ouvre un article Philum (local ou distant) dans une popup'],"popmsqt"=>['affiche le contenu d\'une entrée msql dans une popup ; [system_program*gnu_1§GNU:popmsqt] '],"popread"=>['affiche le contenu d\'un article dans une popup'],"poptxt"=>['affiche le contenu d\'un fichier texte dans une popup'],"popurl"=>['ouvre une page web dans une popup'],"prod"=>['article sous forme de produit de boutique en ligne'],"pub"=>['publicité d\'un article  [ID§option:pub] 
- par défaut : renvoie un simple lien du titre
- §1 : panneau d\'article en mode 1 (preview=false)
- §2 : panneau d\'article en mode 2 (preview=true)
- §3 : panneau d\'article en mode 3 (preview=full)
- §4 : template \'pub_art\''],"punct"=>['applique les règles typographiques'],"radio"=>['pile de fichiers audio depuis l\'espace disque [dev/music:radio] (1 par article, le module fabrique une playlist)'],"read"=>['place le contenu d\'un article'],"rename_img"=>['enregistre l\'article en affectant un nom random aux images à importer, si par exemple elles ne sont différenciées que par le nom de la variable (après le \'?\')'],"replace"=>['remplacement de texte'],"revert"=>['revient à la version courante'],"rss_art"=>['contenu d\'un article diffusé en rss'],"rss_input"=>['flux rss'],"rss_read"=>['contenu d\'un article d\'un autre site philum'],"scan"=>['retourne le contenu d\'un document placé dans le répertoire utilisateur, §1 interprète les connecteurs du contenu'],"search"=>['résultats d\'une recherche (dépendant de time_system)'],"shop"=>['articles liés par hiérarchie sous forme de tableau de produits d\'une boutique en ligne 
(indiquer les tables personnalisées \'prix\' et \'référence\''],"size"=>['taille du texte [text§24:size] '],"swf"=>['Renvoie un lien qui renvoie une popup en ajax où s\'affiche l\'animation Flash. [width/large§src:swf]'],"t"=>['css \'txtit\' (titres)'],"tables"=>['efface les tableaux'],"thumb"=>['fabrique une miniature d\'une image avec des dimensions personnalisées : [img.jpg§140/100:thumb]'],"twitter"=>['appelle un twit depuis son ID, ou un flux depuis le nom d\'utilisateur, à travers l\'API Twitter'],"version"=>['num version'],"video"=>['lit une vidéo youtube daily vimeo rutube etc... d\'après leur id. §1 renvoie un lien qui ouvre une popup'],"play"=>['lit une vidéo directement'],"w"=>['affiche le lien en entier'],"web"=>['renvoie le contenu d\'une page html et l\'interprète'],"webpage"=>['affiche une page web dans une popup (utilisant le plugin \'suggest\' : se réfère aux définitions de sites ou à l\'entête)'],"mktable"=>['formate les données csv en tableau (virgule et saut de ligne) '],"svgcode"=>['crée un svg depuis des connecteurs. §width/height'],"popmsql"=>['affiche le contenu d\'une base msql dans une popup ; [public_atomic§GNU:popmsql]'],":pre"=>['efface les connecteurs :pre'],"image"=>['ouvre comme image sans l\'importer, n\'importe quel format'],"plugin"=>['se comporte comme un connecteur habituel : name§param:plugin'],"slides"=>['crée un diaporama d\'après les données dans le connecteur, séparées par un saut de ligne ou par --'],"fluid"=>['crée une image dont l\'ensemble se découvre lors du scroll (§hauteur) [img.jpg§100:fluid]'],"floatleft"=>['float left'],"floatright"=>['float right'],"sigle"=>['code des monnaies (euro, dollar, yen...)'],"caviar"=>['permet de caviarder du texte'],"bkgclr"=>['couleur de fond de texte : [texte§yellow:bkgclr]'],"dev"=>['le contenu est réservé à auth(4)'],":color"=>['couleur de texte'],":bkgclr"=>['couleur de fond de texte'],"u-red"=>['souligne en rouge'],"u-blue"=>['souligne en bleu'],"u-green"=>['souligne en vert'],"u-purple"=>['souligne en violet'],"toggle"=>['contenu affichable [content§title:toggle]'],"exec"=>['exécute du code'],"api"=>['appel de l\'Api'],"papi"=>['bouton d\'appel de l\'Api'],"tag"=>['appelle le résultat d\'un tag : [mot-clef§classeTag:tag]'],"picto"=>['affiche un picto à partir de sa nomination'],"ascii"=>['affiche un ascii à partir de sa nomination'],"mercury"=>['affiche le rendu d\'une page via l\'Api Mercury'],"webview"=>['affiche au survol une previsualisation du lien (qui propose un lien vers un import)'],"wiki"=>['renvoie l\'entête de la page wikipedia s\'il y a un texte lié, sinon renvoie son contenu entier.']];