<?php
//philum_microsql_admin_design_1

$admin_design_1["1"]=array('','','body','7','1','','font-family:Arial, Verdana, sans-serif; font-size:11px; border:0; margin:0; padding:0; ');
$admin_design_1["2"]=array('','','a','','','','cursor:pointer; text-decoration:none; ');
$admin_design_1["3"]=array('','','h1','','','','font-family:Impact, Helvetica, Verdana; font-size:24px; margin:0px; padding:0px; ');
$admin_design_1["4"]=array('','','h2','||5','','4','font-family: Geneva, Arial, Helvetica, sans-serif; 
font-size:16px; font-weight:bolder; font-variant:small-caps; border:0px; margin:0px 4px; padding:4px; ');
$admin_design_1["5"]=array('','','h3','5','','4','font-size:18px; font-weight:700; padding:4px 9px 0px 9px;');
$admin_design_1["6"]=array('','','h4','5','','4','font-size:14px; margin:0px; ');
$admin_design_1["7"]=array('','','td','','3','4','border:0px; padding:2px;');
$admin_design_1["8"]=array('','','table','','','4','font-size:11px; margin:0px; ');
$admin_design_1["9"]=array('','','blockquote','','','4','font-size:13px; margin:4px; padding:4px; line-height:15px; border-width:1px 1px 1px 8px; border-style:solid; ');
$admin_design_1["10"]=array('','','img','','','','border:0px; ');
$admin_design_1["11"]=array('','','hr','','','4','');
$admin_design_1["12"]=array('','','ul','','','','list-style:none; padding:0; margin:0; ');
$admin_design_1["13"]=array('','','li','','','','line-height:15px; padding-right:5px;');
$admin_design_1["14"]=array('','','input','7','1','4','border:none; margin:0px; ');
$admin_design_1["15"]=array('','','textarea','4','1','7','border:none; margin:1px solid; ');
$admin_design_1["16"]=array('','','select','3','7','4','background:black; padding:0px; ');
$admin_design_1["17"]=array('','','submit','6','2','4','');
$admin_design_1["18"]=array('','','form','','','','padding:0px; margin:0px; ');
$admin_design_1["19"]=array('banner','','','','','','');
$admin_design_1["20"]=array('page','','','8','','4','text-align:left; margin:0 auto; width:750px; padding:2px; ');
$admin_design_1["21"]=array('leftbar','','','||','','','float:left; width:150px; ');
$admin_design_1["22"]=array('rightbar','','','||','','','float:right; width:0px; ');
$admin_design_1["23"]=array('menu','','','|8|5','','','');
$admin_design_1["24"]=array('content','','','|7|5','','||5','margin-left:150px; margin-right:0px; margin-bottom:10px; padding:0px 10px; ');
$admin_design_1["25"]=array('footer','','','','3','','clear:both; text-align:center; margin-top:5px;');
$admin_design_1["26"]=array('scroll','','','','3','','overflow:auto; height:400px;');
$admin_design_1["27"]=array('','tab','','5','4','2','font-family:Verdana; font-size:11px; padding:1px; margin:0 0 20px 0; ; ');
$admin_design_1["28"]=array('','tabb','','7|7|5','3','2','font-family:Verdana; font-size:11px; padding:1px; margin:1px;');
$admin_design_1["29"]=array('','tabc','','7|7|5','5','2','font-family:Verdana; font-size:11px; padding:1px; margin:1px;');
$admin_design_1["30"]=array('','htab','','','','','float:left; width:282px; #width:278px; margin:4px; align:center; ');
$admin_design_1["31"]=array('','htab3','','','','','float:left; width:185.33333333333px; #width:181.33333333333px; margin:4px; align:center; ');
$admin_design_1["32"]=array('','panel','','8','3||6','2','font-family:Verdana; padding:4px 3px; margin-bottom:5px; ');
$admin_design_1["33"]=array('','justy','','7','6','','font-family:Lucida Grande, Trebuchet MS, Arial; 
font-size:15px; text-align:justify; padding:4px 6px;');
$admin_design_1["34"]=array('','imgl','','5','','','float:left; margin:0px 4px 0px 0px; padding:4px 0px 2px 2px;');
$admin_design_1["35"]=array('','imgr','','5','','','float:right; margin:0px 0px 0px 4px; padding:0px 0px 0px 2px;');
$admin_design_1["36"]=array('','txtot','','5','','','font-family:impact; font-size:20px; margin-left:4px; ');
$admin_design_1["37"]=array('','txtit','','8','','','font-family:Geneva, Arial, Helvetica, sans-serif; 
font-size:16px; font-variant:small-caps; font-weight:700; ');
$admin_design_1["38"]=array('','txtblc, .txtnoir, .txtred, .txtx, .txtcadr, .txtyl, .rss ','','','','','font-family:Arial, Helvetica, sans-serif; font-size:11px; margin:0px; padding:1px 3px 0px 4px; letter-spacing:1px; line-height:18px; border-width:thin; border-style:solid; ');
$admin_design_1["39"]=array('','txtcadr','','5|7','4','1','font-weight:800; line-height:12px; padding-bottom:2px;');
$admin_design_1["40"]=array('','txte','','','','5','font-size:13px; margin:4px; padding:2px; line-height:15px; border-width:1px 1px 1px 8px; border-style:solid; ');
$admin_design_1["41"]=array('','txtx','','8|8|5','1||6','4','');
$admin_design_1["42"]=array('','txtblc','','8','6','','background:white; color:black; ');
$admin_design_1["43"]=array('','txtred','','|5|8','6|6|6','|5|5','border-color:red; ');
$admin_design_1["44"]=array('','txtnoir','','1|6|6','','|6|6','background:black; color:white; ');
$admin_design_1["45"]=array('','txtclr','','','','','color:red; font-weight:bold; ');
$admin_design_1["46"]=array('','txtyl','','7|7|1','','||1','background:red; ');
$admin_design_1["47"]=array('','txtalert','','5','','','border:medium double red; ');
$admin_design_1["48"]=array('','txtsmall','','5','6','6','font-family:Arial; font-size:10px; padding:0px;');
$admin_design_1["49"]=array('','txtsmall2','','8','','','font-family:Arial; font-size:9px; padding:0px; ');
$admin_design_1["50"]=array('','txtbox','','7|7|','1|1|5','4','font-size:11px; border-bottom:1px solid;');
$admin_design_1["51"]=array('','stabilo','','','4','','');
$admin_design_1["52"]=array('','rss','','','||7','','font-size:9px; color:white; border:1px solid white; font-weight:800; background:#FF8800; padding:1px 2px 0px 3px;');
$admin_design_1["53"]=array('','txtyu','','8|8|5','||6','','font-size:11px; margin:2px 0px; display:block;  margin-bottom:5px; border-bottom:0px dashed; clear:left; ');
$admin_design_1["54"]=array('','txtyub','','8|8|5','||6','','font-size:11px; margin:2px 0px; display:block; margin-bottom:5px; clear:left;');
$admin_design_1["55"]=array('','txtyug','','8|5|5','3|3|6','','font-size:11px; margin:2px 0px; display:block;  margin-bottom:5px; ');
$admin_design_1["56"]=array('','txtyugb','','8|8|5','3|3|6','','font-size:12px; margin:4px 0px; padding:1px 0px; display:block; ');
$admin_design_1["57"]=array('','miniprod','','8|8|5','3|3|6','','margin:4px; padding:4px; display:block; text-align:center; border-width:1px; border-style:solid; ');
$admin_design_1["58"]=array('content','txtyug','','','','','font-family: Verdana; font-size:11px; margin-bottom:10px; min-height:70px;');
$admin_design_1["59"]=array('line','','','8','','','margin:0px; padding:0px; text-align:center; font-family:Impact; font-size:10px; font-weight:lighter; ');
$admin_design_1["60"]=array('','lina','','','','','float:left; width:16px; list-style-type:none; color:#bbbbbb; ');
$admin_design_1["61"]=array('','linc','','8','','','float:left; width:16px; list-style-type:none; ');
$admin_design_1["62"]=array('','clear','','','','','clear:left;');
$admin_design_1["63"]=array('','console','','8||8','1||6','4','font-family:Courier New, Courier, mono; font-style:code; line-height:18px; font-size:13px; color:green; background:black; border:4px double white; margin:10px; padding:10px; filter:alpha(opacity=100); opacity:1.00; ');
$admin_design_1["64"]=array('navigation','','','','','','width:auto; font-size:15px; ');
$admin_design_1["65"]=array('navigation','','ul','','','','font-size:12px; width:auto;');
$admin_design_1["66"]=array('navigation','','ul li','|2|5','|4|3','','');
$admin_design_1["67"]=array('navigation','','ul li a','','','','line-height:1em; padding:2px;');
$admin_design_1["68"]=array('navigation','','ul li ul.active','','','','width:150px; padding-top:2px; opacity: 0.9;');
$admin_design_1["69"]=array('navigation','','li ul ul','','','','margin: 0px 0 0 150px;');
$admin_design_1["70"]=array('navigation','','ul li ul li','','','','width:150px;');
$admin_design_1["71"]=array('navigation','','ul li ul li a','','','','line-height:1em; padding:2px;');

?>