<?php //philum/msql/public_mods_3
$r=array(
'_menus_'=>array('block','module','param','title','condition','command','option','cache','hide','template','nobr'),
2=>array('system','blocks','banner menu  content footer','','','','','','','',''),
3=>array('system','design','2','','','','','','','',''),
4=>array('content','Page_titles','','','home','','','','','','1'),
6=>array('content','prev_next','','','art','','','','1','','1'),
7=>array('footer','credits','','','','','','1','','','1'),
8=>array('footer','chrono','','','','','','','','','1'),
9=>array('footer','contact','','','','','','1','','','1'),
10=>array('content','Page_titles','hello','','art','','no','','','','1'),
12=>array('content','LOAD','','','art','','','','0','',''),
13=>array('newsletter','articles','preview=false','tit','','articles','','','','',''),
14=>array('system','banner','640','','','','','','','',''),
15=>array('system','content','640','','','','','','','',''),
17=>array('banner','search','Recherche','','','','right','','','','1'),
18=>array('banner','Banner','','','','','','1','','','1'),
19=>array('system','template','','','','','','','','',''),
20=>array('system','art_mod','related_arts§lié à, related_by§lié par','title','','tabmods','','','','',''),
21=>array('system','apps','','0','','','0','','','',''),
22=>array('content','LOAD','','','home','','','','0','',''),
23=>array('menu','link','Home§home:picto','','','','','','1','',''),
24=>array('system','desktop','to bottom,#002594,#06999e,#878787,#bf1755,#4f004f','','','','','','','',''),
25=>array('content','LOAD','','','cat','','','','0','',''),
26=>array('content','connector','http://philum.net/236:rss_read','','home','','article','','0','',''),
27=>array('menu','categories','','','','','','','1','','1'),
29=>array('system','popadmin','picto','','','','search import','','','',''));
?>