<?php //msql/newsnet_citation_11
$r=["_menus_"=>['Traité sur l\'Espace'],
"1"=>['Article 1 (1) : L\'exploration et l\'utilisation de l\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, doivent se faire pour le bien et dans l\'intérêt de tous les pays, quelque soit le stade de leur développement économique ou scientifique; elles sont l\'apanage de l\'humanité tout entière.'],
"2"=>['Article 1 (2) : L\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, peut être exploré et utilisé librement par tous les États sans aucune discrimination, dans des conditions d\'égalité et conformément au droit international, toutes les régions des corps célestes devant être librement accessibles.'],
"3"=>['Article 1 (3) : Les recherches scientifiques sont libres dans l\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, et les États doivent faciliter et encourager la coopération internationale dans ces recherches.'],
"4"=>['Article 2 : L\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, ne peut faire l\'objet d\'appropriation nationale par proclamation de souveraineté, ni par voied\'utilisation ou d\'occupation, ni par aucun autre moyen.'],
"5"=>['Article 3 : Les activités des États parties au Traité relatives à l\'exploration et à l\'utilisation de l\'espace extra-atmosphérique, y compris la Lune et les autres corps célestes, doivents\'effectuer conformément au droit international, y compris la Charte des Nations Unies,en vue de maintenir la paix et la sécurité internationales et de favoriser la coopération etla compréhension internationales.'],
"6"=>['Article 4 : Les États parties au Traité s\'engagent à ne mettre sur orbite autour de la Terre aucun objet porteur d\'armes nucléaires ou de tout autre type d\'armes de destruction massive, à ne pas installer de telles armes sur des corps célestes et à ne pas placer de telles armes, de toute autre manière, dans l\'espace extra-atmosphérique.'],
"7"=>['Article 4 (suite) : Tous les États parties au Traité utiliseront la Lune et les autres corps célestes exclusivement à des fins pacifiques. Sont interdits sur les corps célestes l\'aménagement de bases et installations militaires et de fortifications, les essais d\'armes de tous types et l\'exécution de man&oelig;uvres militaires. N\'est pas interdite l\'utilisation de personnel militaire à des fins de recherche scientifique ou à toute autre fin pacifique. N\'est pas interdite non plus l\'utilisation de tout équipement ou installation nécessaire à l\'exploration pacifique de la Lune et des autres corps célestes.'],
"8"=>['Article 5 : Les États parties au Traité considéreront les astronautes comme des envoyés de l\'humanité dans l\'espace extra-atmosphérique et leur prêteront toute l\'assistance possible en cas d\'accident, de détresse ou d\'atterrissage forcé sur le territoire d\'un autre État partie au Traité ou d\'amerrissage en haute mer. En cas d\'un tel atterrissage ou amerrissage, le retour des astronautes à l\'État d\'immatriculation de leur véhicule spatial devra être effectué promptement et en toute sécurité.'],
"9"=>['Article 5 (2) : Lorsqu\'ils poursuivront des activités dans l\'espace extra-atmosphérique et sur les corps célestes, les astronautes d\'un État partie au Traité prêteront toute l\'assistance possible aux astronautes des autres États parties au Traité.'],
"10"=>['Article 5 (3) : Les États parties au Traité porteront immédiatement à la connaissance des autres États parties au Traité ou du Secrétaire général de l\'Organisation des Nations Unies tout phénomène découvert par eux dans l\'espace extra-atmosphérique, y compris la Lune et les corps célestes, qui pourrait présenter un danger pour la vie ou la santé des astronautes.'],
"11"=>['Article 8 : L\'État partie au Traité sur le registre duquel est inscrit un objet lancé dans l\'espace extra-atmosphérique conservera sous sa juridiction et son contrôle ledit objet et tout le personnel dudit objet, alors qu\'ils se trouvent dans l\'espace extra-atmosphérique ou sur un corps céleste. Les droits de propriété sur les objets lancés dans l\'espace extra-atmosphérique, y compris les objets amenés ou construits sur
un corps céleste, ainsi que sur leurs éléments constitutifs, demeurent entiers lorsque ces objets ou éléments se trouvent dans l\'espace extra-atmosphérique ou sur un corps céleste, et lorsqu\'ils reviennent sur la Terre.']];