<?php //msql/newsnet_citation_5
$r=["_menus_"=>['Principes des Nations Unies'],
"1"=>['Article 2.1 - L\'Organisation des Nations Unies et ses Membres, dans la poursuite des buts énoncés à l\' Article 1, doivent agir conformément aux principes suivants :'],
"2"=>['Article 2.2 - L\'Organisation est fondée sur le principe de l\'égalité souveraine de tous ses Membres.'],
"3"=>['Article 2.3 - Les Membres de l\'Organisation, afin d\'assurer à tous la jouissance des droits et avantages résultant de leur qualité de Membre, doivent remplir de bonne foi les obligations qu\'ils ont assumées aux termes de la présente Charte.'],
"4"=>['Article 2.4 - Les Membres de l\'Organisation règlent leurs différends internationaux par des moyens pacifiques, de telle manière que la paix et la sécurité internationales ainsi que la justice ne soient pas mises en danger.'],
"5"=>['Article 2.5 - Les Membres de l\'Organisation s\'abstiennent, dans leurs relations internationales, de recourir à la menace ou à l\'emploi de la force, soit contre l\'intégrité territoriale ou l\'indépendance politique de tout État, soit de toute autre manière incompatible avec les buts des Nations Unies.'],
"6"=>['Article 2.5 - Les Membres de l\'Organisation donnent à celle-ci pleine assistance dans toute action entreprise par elle conformément aux dispositions de la présente Charte et s\'abstiennent de prêter assistance à un État contre lequel l\'Organisation entreprend une action préventive ou coercitive.'],
"7"=>['Article 2.6 - L\'Organisation fait en sorte que les États qui ne sont pas Membres des Nations Unies agissent conformément à ces principes dans la mesure nécessaire au maintien de la paix et de la sécurité internationales.'],
"8"=>['Article 2.7 - Aucune disposition de la présente Charte n\'autorise les Nations Unies à intervenir dans des affaires qui relèvent essentiellement de la compétence nationale d\'un État ni n\'oblige les Membres à soumettre des affaires de ce genre à une procédure de règlement aux termes de la présente Charte; toutefois, ce principe ne porte en rien atteinte à l\'application des mesures de coercition prévues au Chapitre VII.'],
"9"=>['Article 106 - En attendant l\'entrée en vigueur des accords spéciaux visés à l\'article 43* qui, de l\'avis du Conseil de sécurité, lui permettent de commencer à exercer ses responsabilités en vertu de l\'article 42*, les parties à la déclaration des quatre nations, signée à Moscou le 30 octobre 1943, et la France, conformément aux dispositions du paragraphe 5 de ladite déclaration, se consulteront et, selon que de besoin, avec d\'autres Membres de l\'Organisation des Nations unies en vue d\'une action commune au nom de l\'Organisation qui pourra être nécessaire dans le but de maintenir la paix et la sécurité internationales.']];