<?php
//philum_microsql_public_rssurl_sav
$r["_menus_"]=array('rssurl','name','root','bot');
$r[1]=array('www.mondialisation.ca/feed/ ','mondialisation','presse libre','');
$r[2]=array('lesactualitesdudroit.20minutes-blogs.fr/index.rss','lesactualitesdudroit','blogs');
$r[3]=array('lesmoutonsenrages.fr/feed/','lesmoutonsenrages','blogs');
$r[4]=array('lesmotsontunsens.com/rss.xml','lesmotsontunsens','blogs');
$r[5]=array('monde-diplomatique.fr/recents.xml ','monde-diplomatique','news','1');
$r[6]=array('www.pressegauche.org/spip.php?page=backend','pressegauche','blogs');
$r[7]=array('www.info-palestine.net/backend.php','info-palestine','presse libre','1');
$r[8]=array('resistance71.wordpress.com/feed/','resistance71','blogs');
$r[9]=array('michelcollon.info/spip.php?page=backend&id_rubrique=3','michelcollon','presse libre','1');
$r[10]=array('contretemps.eu/rss','contretemps','blogs');
$r[11]=array('feeds2.feedburner.com/internetactu/bcmJ','internetactu','web');
$r[12]=array('www.politis.fr/spip.php?page=backend&id_rubrique=60','vive le feu!','blogs');
$r[13]=array('bastamag.net/spip.php?page=backend','bastamag','news');
$r[14]=array('www.tlaxcala-int.org/rss_lg.asp?lg_rss=fr','tlaxcala-int','presse libre','');
$r[15]=array('www.ism-france.org/rss.xml','ism-france','presse libre','1');
$r[16]=array('altermonde-sans-frontiere.com/spip.php?page=backend','altermonde','presse libre','');
$r[17]=array('numerama.com/rss/news.rss','numerama','web','1');
$r[18]=array('www.legrandsoir.info/spip.php?page=backend','legrandsoir','presse libre','1');
$r[19]=array('www.elcorreo.eu.org/spip.php?page=backend','elcorreo','presse libre','1');
$r[20]=array('nonfiction.fr/rss-actualites.xml','nonfiction','blogs');
$r[21]=array('framablog.org/index.php/feed/atom','framasoft','web');
$r[22]=array('blog.monolecte.fr/feed/rss2','monolecte','blogs');
$r[23]=array('gillesbonafi.blogspot.com/feeds/posts/default','gillesbonafi','blogs');
$r[24]=array('www.wikistrike.com/rss','wikistrike','presse libre','');
$r[25]=array('www.bakchich.info/rss.xml','bakchich','news');
$r[26]=array('www.agoravox.fr/spip.php?page=backend&id_rubrique=41','agoravox','blogs');
$r[27]=array('bellaciao.org/fr/backend.php3','bellaciao','news');
$r[28]=array('www.alterinfo.net/xml/syndication.rss','alterinfo','news');
$r[29]=array('www.oulala.info/feed/','oulala','presse libre','');
$r[30]=array('www.regards.fr/spip.php?page=backend','regards','blogs');
$r[31]=array('www.gurumed.org/feed/','gurumed','science');
$r[32]=array('www.journaldelascience.fr/rss-home.xml','delascience','science');
$r[33]=array('wired.com/wiredscience/feed/','wired/science','science');
$r[34]=array('phys.org/rss-feed/','phys.org','science');
$r[35]=array('projetcelestia.com/feed/','projetcelestia','science');
$r[36]=array('naturealerte.blogspot.com/feeds/posts/default','naturealerte','science');
$r[37]=array('feeds.feedburner.com/DailyGeekShow?format=xml','dailygeekshow','web');
$r[38]=array('www.begeek.fr/feed','begeek','web');
$r[39]=array('almanar.com.lb/french/rss.php','almanar','news');
$r[40]=array('feeds.feedburner.com/oumma?format=xml','oumma','presse libre','');
$r[41]=array('acrimed.org/spip.php?page=backend','acrimed','news');
$r[42]=array('www.jetdencre.ch/feed','jetdencre','blogs');
$r[43]=array('www.gizmodo.fr/feed','gizmodo','web');
$r[44]=array('www.primitivi.org/spip.php?page=backend','primitivi','blogs');
$r[45]=array('blog.agone.org/feed/rss2','agone','blogs');
$r[46]=array('cadtm.org/spip.php?page=backend-fr','cadtm','presse libre','');
$r[47]=array('europalestine.eu/spip.php?page=backend','capjo','presse libre','');
$r[48]=array('cetri.be/spip.php?page=backend&id_rubrique=38','cetri','news');
$r[49]=array('lmsi.net/spip.php?page=backend','lmsi','news');
$r[50]=array('irinnews.org/french.xml','irin','news');
$r[51]=array('www.4emesinge.com/feed/','4emesinge','blogs');
$r[52]=array('fr.sott.net/xml_engine/signs_rss','sott','presse libre','');
$r[53]=array('fawkes-news.blogspot.com/feeds/posts/default','fawkes-news','presse libre','');
$r[54]=array('http://www.vineyardsaker.fr/feed/','vineyardsaker','presse libre','');
$r[55]=array('huffingtonpost.fr/feeds/verticals/france/index.xml','huffingtonpost','web');
$r[56]=array('mrmondialisation.org/categorie/articles/feed/atom/','mrmondialisation','blogs');
$r[57]=array('arretsurinfo.ch/feed/','arretsurinfo','blogs');
$r[58]=array('popsci.com/rss.xml','popsci','science','');
$r[59]=array('ilfattoquotidiano.fr/feed/','ilfattoquotidiano','presse libre','');

?>